// Clase interactiva · 3ro BGU · Evaluación de fuentes y uso ético
(function () {
  let INK, PAPER, MUTE, LINE, TEAL, AMB, RED, BLUE, OKC, CARD, SINK, DARK, SUNK, SELB, OFF, DIS, DIST, FT, F1, F2, CLARO;
  const TEMAS = { claro: { INK: '#14181c', PAPER: '#f4f6f7', MUTE: '#4a5760', LINE: '#c3ced4', TEAL: '#0b7d6e', AMB: '#a86200', RED: '#c23b30', BLUE: '#2456b8', OKC: '#1d7a44', CARD: '#ffffff', SINK: '#14181c', DARK: '#ffffff', SUNK: '#eef2f4', SELB: '#ffe7a3', OFF: '#e1e7ea', DIS: '#d5dde1', DIST: '#6f7c84', FT: 'clamp(19px,1.7vw,30px)', F1: 'clamp(34px,4.2vw,76px)', F2: 'clamp(23px,2.3vw,40px)' },
    oscuro: { INK: '#e8f1f2', PAPER: '#0b1218', MUTE: '#9fb0ba', LINE: '#2c3e4a', TEAL: '#3fd0b8', AMB: '#f0a726', RED: '#ff7b72', BLUE: '#6ea8ff', OKC: '#7fe0a0', CARD: '#13202a', SINK: '#14181c', DARK: '#06121a', SUNK: SUNK, SELB: SELB, OFF: OFF, DIS: DIS, DIST: DIST, FT: 'clamp(17px,1.5vw,24px)', F1: 'clamp(30px,3.6vw,64px)', F2: 'clamp(21px,2vw,34px)' } };
  function TEMA(t) { const x = TEMAS[t] || TEMAS.claro; ({ INK, PAPER, MUTE, LINE, TEAL, AMB, RED, BLUE, OKC, CARD, SINK, DARK, SUNK, SELB, OFF, DIS, DIST, FT, F1, F2 } = x); CLARO = t !== 'oscuro'; }
  const HEAD = "'Archivo Black',sans-serif", MONO = "'IBM Plex Mono',monospace";

  function make(React) {
    const tm = window.__claseTema || 'claro'; if (make.c && make.t === tm) return make.c; make.t = tm; TEMA(tm);
    const { useState, useEffect, useRef } = React, h = React.createElement;
    const D = (st, ...ch) => h('div', { style: st }, ...ch);
    const T = (t, st) => h('div', { style: Object.assign({ fontSize: FT, lineHeight: 1.45, color: INK, textWrap: 'pretty' }, st || {}) }, t);
    const H1 = (t, st) => h('div', { style: Object.assign({ textShadow: CLARO ? 'none' : '0 0 22px rgba(63,208,184,.22)', fontFamily: HEAD, fontSize: F1, lineHeight: 1.04, color: INK, letterSpacing: '-.01em', textWrap: 'balance' }, st || {}) }, t);
    const H2 = (t, st) => h('div', { style: Object.assign({ fontFamily: HEAD, fontSize: F2, lineHeight: 1.1, color: INK }, st || {}) }, t);
    const K = (t, c) => h('div', { style: { fontFamily: MONO, fontSize: 'clamp(12px,.95vw,16px)', letterSpacing: '.14em', fontWeight: 600, color: c || MUTE, textTransform: 'uppercase' } }, t);
    const B = t => h('b', null, t);
    const Card = (st, ...ch) => D(Object.assign({ background: CARD, border: '2px solid ' + LINE, borderRadius: 10, padding: 'clamp(14px,1.4vw,24px)', display: 'flex', flexDirection: 'column', gap: 12, minWidth: 0 }, st || {}, st && st.borderColor ? { boxShadow: GLOW(st.borderColor) } : {}), ...ch);
    const Btn = (t, onClick, o) => { o = o || {}; return h('button', { onClick, disabled: o.dis, style: { fontFamily: o.head === false ? 'inherit' : HEAD, fontSize: o.fs || 'clamp(15px,1.25vw,20px)', padding: o.pad || '12px 20px', background: o.dis ? DIS : o.bg || INK, color: o.dis ? DIST : o.c || DARK, border: '2px solid ' + (o.dis ? DIS : o.bd || o.bg || INK), boxShadow: o.dis || o.bg === CARD ? 'none' : '0 0 18px ' + (o.bg || INK) + '33', cursor: o.dis ? 'default' : 'pointer', textAlign: 'left', lineHeight: 1.2 } }, t); };
    const Chip = (t, on, onClick, col) => h('button', { onClick, style: { fontFamily: 'inherit', fontWeight: 600, fontSize: 'clamp(14px,1.15vw,19px)', padding: '10px 14px', background: on ? (col || INK) : CARD, color: on ? DARK : INK, border: '2px solid ' + (on ? (col || INK) : LINE), cursor: 'pointer', textAlign: 'left', lineHeight: 1.25 } }, t);
    const Row = (st, ...ch) => D(Object.assign({ display: 'flex', flexWrap: 'wrap', gap: 10, alignItems: 'center' }, st || {}), ...ch);
    const Grid = (min, ...ch) => D({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,' + min + 'px),1fr))', gap: 'clamp(12px,1.4vw,22px)', alignItems: 'start' }, ...ch);
    const Say = (p, txt) => p.say ? h('button', { onClick: () => p.say(txt), title: 'Escuchar', style: { fontFamily: MONO, fontSize: 13, fontWeight: 700, padding: '6px 10px', background: CARD, border: '2px solid ' + INK, cursor: 'pointer', alignSelf: 'flex-start' } }, '🔊 ESCUCHAR') : null;
    const Fb = (ok, txt) => D({ border: '3px solid ' + (ok ? OKC : RED), background: ok ? 'rgba(127,224,160,.12)' : 'rgba(255,123,114,.12)', padding: '14px 18px', display: 'flex', flexDirection: 'column', gap: 6 }, D({ fontFamily: HEAD, fontSize: 'clamp(17px,1.4vw,22px)', color: ok ? OKC : RED }, ok ? '¡Funciona!' : 'Todavía no funciona'), T(txt, { fontSize: 'clamp(15px,1.2vw,19px)' }));
    const Sel = (val, opts, set) => h('select', { value: val, onChange: e => set(e.target.value), style: { fontFamily: 'inherit', fontSize: 'clamp(15px,1.2vw,19px)', fontWeight: 600, padding: '9px 10px', border: '2px solid ' + INK, background: CARD, color: INK, maxWidth: '100%' } }, ...opts.map(o => h('option', { key: o[0], value: o[0] }, o[1])));
    const Slider = (lab, val, min, max, set, unit) => D({ display: 'flex', flexDirection: 'column', gap: 6, minWidth: 0 }, Row({ justifyContent: 'space-between' }, K(lab, INK), D({ fontFamily: HEAD, fontSize: 'clamp(18px,1.6vw,26px)', whiteSpace: 'nowrap', flex: 'none' }, val + (unit || ''))), h('input', { type: 'range', min, max, value: val, onChange: e => set(Number(e.target.value)), style: { width: '100%', accentColor: TEAL } }));

    // ---------- Diagrama de flujo ----------
    function Flujo({ nodos, activo, err, compact }) {
      const fs = compact ? 'clamp(12px,1vw,16px)' : 'clamp(13px,1.1vw,18px)';
      const forma = (n, act, key) => {
        const bg = act ? '#ffe7a3' : n.bad ? 'rgba(255,123,114,.12)' : '#fff', bd = n.bad ? RED : SINK, base = { fontSize: fs, fontWeight: 600, color: SINK, textAlign: 'center', lineHeight: 1.2, boxShadow: act ? '0 0 0 4px ' + AMB : 'none' };
        if (n.t === 'ini') return h('div', { key, style: Object.assign(base, { border: '3px solid ' + bd, borderRadius: 999, padding: '8px 22px', background: bg }) }, n.txt);
        if (n.t === 'io') return h('div', { key, style: Object.assign(base, { border: '3px solid ' + bd, padding: '8px 22px', background: bg, transform: 'skewX(-14deg)' }) }, h('div', { style: { transform: 'skewX(14deg)' } }, n.txt));
        if (n.t === 'dec') return h('div', { key, style: { position: 'relative', width: 'clamp(170px,15vw,240px)', height: 'clamp(84px,7vw,110px)', display: 'flex', alignItems: 'center', justifyContent: 'center' } },
          h('svg', { viewBox: '0 0 200 100', preserveAspectRatio: 'none', style: { position: 'absolute', inset: 0, width: '100%', height: '100%' } }, h('polygon', { points: '100,3 197,50 100,97 3,50', fill: bg, stroke: bd, strokeWidth: 3, vectorEffect: 'non-scaling-stroke' })),
          h('div', { style: Object.assign(base, { position: 'relative', padding: '0 34px', boxShadow: 'none' }) }, n.txt), act ? h('div', { style: { position: 'absolute', inset: -6, border: '3px solid ' + AMB, pointerEvents: 'none', clipPath: 'polygon(50% 0,100% 50%,50% 100%,0 50%)' } }) : null);
        return h('div', { key, style: Object.assign(base, { border: '3px solid ' + bd, padding: '8px 18px', background: bg }) }, n.txt);
      };
      const flecha = k => h('div', { key: k, style: { width: 3, height: compact ? 14 : 20, background: SINK, position: 'relative' } }, h('div', { style: { position: 'absolute', bottom: -2, left: -5, borderLeft: '6.5px solid transparent', borderRight: '6.5px solid transparent', borderTop: '8px solid ' + SINK } }));
      const out = [];
      nodos.forEach((n, i) => {
        if (i) out.push(flecha('f' + i));
        if (n.t === 'dec') {
          out.push(forma(n, activo === i, 'n' + i));
          const rama = (lado, r, ak) => D({ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, minWidth: 0 }, D({ fontFamily: MONO, fontWeight: 700, fontSize: 14, color: lado === 'SÍ' ? OKC : RED }, lado), flecha('x'), forma(r, activo === ak, ak));
          out.push(h('div', { key: 'r' + i, style: { display: 'flex', gap: 'clamp(14px,2vw,40px)', justifyContent: 'center', alignItems: 'flex-start' } }, rama('SÍ', n.si, i + 's'), rama('NO', n.no, i + 'n')));
        } else out.push(forma(n, activo === i, 'n' + i));
      });
      return D({ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 0, padding: '10px 4px' }, ...out, nodos.loop ? D({ fontFamily: MONO, fontSize: 14, fontWeight: 700, marginTop: 8, color: SINK }, '↺ ' + nodos.loop) : null);
    }

    // ---------- Simulaciones SVG ----------
    function Planta({ hum, bomba }) {
      const s = hum < 25 ? 'seca' : hum > 85 ? 'ahogada' : 'bien', hoja = s === 'seca' ? '#b9a25a' : s === 'ahogada' ? '#5d8a6a' : '#2f9a55', caida = s === 'seca' ? 18 : 0;
      return h('svg', { viewBox: '0 0 220 200', style: { width: '100%', maxWidth: 260, height: 'auto', display: 'block' } },
        h('rect', { x: 150, y: 20, width: 50, height: 60, fill: '#dfe9f3', stroke: SINK, strokeWidth: 2 }), h('text', { x: 175, y: 55, textAnchor: 'middle', fontSize: 13, fontFamily: 'IBM Plex Mono', fontWeight: 700 }, 'BOMBA'),
        h('rect', { x: 155, y: 70, width: 40, height: 8, fill: bomba ? BLUE : '#aaa' }), h('path', { d: 'M175 78 V100 H120', fill: 'none', stroke: bomba ? BLUE : '#999', strokeWidth: 6 }),
        bomba ? h('g', null, [0, 1, 2].map(k => h('circle', { key: k, cx: 112 - k * 6, cy: 108 + k * 10, r: 4, fill: BLUE }))) : null,
        h('path', { d: 'M60 140 Q90 ' + (90 + caida) + ' 110 ' + (70 + caida), stroke: '#3a6b35', strokeWidth: 5, fill: 'none' }),
        h('ellipse', { cx: 82, cy: 105 + caida, rx: 22, ry: 10, fill: hoja, transform: 'rotate(' + (-30 + caida) + ' 82 ' + (105 + caida) + ')' }), h('ellipse', { cx: 118, cy: 78 + caida, rx: 22, ry: 10, fill: hoja, transform: 'rotate(' + (20 + caida) + ' 118 ' + (78 + caida) + ')' }),
        h('path', { d: 'M30 140 H130 L120 190 H40 Z', fill: '#b5643a', stroke: SINK, strokeWidth: 2 }), h('rect', { x: 34, y: 140, width: 92, height: 10, fill: hum < 25 ? '#c9a77a' : '#5a3b22' }),
        h('text', { x: 80, y: 172, textAnchor: 'middle', fontSize: 14, fontFamily: 'IBM Plex Mono', fontWeight: 700, fill: '#fff' }, hum + ' %'));
    }
    function Lampara({ on, luz }) {
      const cielo = luz < 300 ? '#22304a' : luz < 600 ? '#e7a96b' : '#bfe0f5';
      return h('svg', { viewBox: '0 0 220 170', style: { width: '100%', maxWidth: 260, height: 'auto', display: 'block' } },
        h('rect', { x: 0, y: 0, width: 220, height: 170, fill: cielo }), h('circle', { cx: 180, cy: 36, r: 18, fill: luz < 300 ? '#f2f2e9' : '#ffd84a' }),
        h('rect', { x: 0, y: 130, width: 220, height: 40, fill: '#8d8a83' }), h('rect', { x: 52, y: 40, width: 6, height: 92, fill: SINK }), h('rect', { x: 52, y: 40, width: 46, height: 6, fill: SINK }),
        on ? h('polygon', { points: '84,52 120,130 48,130', fill: 'rgba(255,226,120,.55)' }) : null, h('circle', { cx: 92, cy: 52, r: 11, fill: on ? '#ffe27a' : '#9a9a9a', stroke: SINK, strokeWidth: 2 }),
        h('text', { x: 110, y: 160, textAnchor: 'middle', fontSize: 13, fontFamily: 'IBM Plex Mono', fontWeight: 700, fill: '#fff' }, on ? 'LÁMPARA ENCENDIDA' : 'LÁMPARA APAGADA'));
    }
    function Semaforo({ luz }) {
      const c = (k, col) => h('circle', { cx: 50, cy: 34 + k * 52, r: 20, fill: luz === k ? col : '#3a3a3a', stroke: '#111', strokeWidth: 2 });
      return h('svg', { viewBox: '0 0 100 180', style: { width: 'clamp(80px,7vw,120px)', height: 'auto', display: 'block' } }, h('rect', { x: 18, y: 6, width: 64, height: 160, rx: 10, fill: '#1c1c1c' }), c(0, '#3ad16b'), c(1, '#ffc531'), c(2, '#ff4b3e'));
    }
    function Puerta({ dist, ang }) {
      const ab = Math.max(0, Math.min(90, ang)) / 90, px = 30 + Math.min(200, dist) * 0.8;
      return h('svg', { viewBox: '0 0 260 170', style: { width: '100%', maxWidth: 300, height: 'auto', display: 'block' } },
        h('rect', { x: 0, y: 140, width: 260, height: 30, fill: '#cfc8b8' }), h('rect', { x: 196, y: 20, width: 56, height: 122, fill: '#e8e4da', stroke: SINK, strokeWidth: 2 }),
        h('rect', { x: 198 + ab * 46, y: 22, width: 52 - ab * 46, height: 118, fill: '#7a5a3a' }), h('rect', { x: 186, y: 26, width: 10, height: 10, fill: BLUE }), h('text', { x: 191, y: 16, textAnchor: 'middle', fontSize: 10, fontFamily: 'IBM Plex Mono', fontWeight: 700 }, 'US'),
        h('g', { transform: 'translate(' + Math.max(16, 200 - px) + ',0)' }, h('circle', { cx: 0, cy: 66, r: 12, fill: SINK }), h('rect', { x: -10, y: 80, width: 20, height: 42, fill: SINK }), h('rect', { x: -10, y: 122, width: 7, height: 18, fill: SINK }), h('rect', { x: 3, y: 122, width: 7, height: 18, fill: SINK })),
        h('text', { x: 130, y: 162, textAnchor: 'middle', fontSize: 11, fontFamily: 'IBM Plex Mono', fontWeight: 700 }, 'distancia: ' + dist + ' cm · servo ' + Math.round(ang) + '°'));
    }
    function Alarma({ on, noche, mov }) {
      return h('svg', { viewBox: '0 0 240 150', style: { width: '100%', maxWidth: 280, height: 'auto', display: 'block' } },
        h('rect', { x: 0, y: 0, width: 240, height: 150, fill: noche ? '#1e2a40' : '#d9ecf7' }), h('rect', { x: 20, y: 30, width: 120, height: 100, fill: noche ? '#2c3a55' : '#f3efe6', stroke: SINK, strokeWidth: 2 }),
        h('text', { x: 80, y: 52, textAnchor: 'middle', fontSize: 11, fontFamily: 'IBM Plex Mono', fontWeight: 700, fill: noche ? '#fff' : SINK }, 'LABORATORIO'),
        mov ? h('g', null, h('circle', { cx: 80, cy: 80, r: 9, fill: '#f0a726' }), h('rect', { x: 72, y: 90, width: 16, height: 30, fill: '#f0a726' })) : null,
        h('rect', { x: 170, y: 50, width: 40, height: 40, fill: on ? RED : '#888', stroke: SINK, strokeWidth: 2 }),
        on ? h('g', null, [0, 1].map(k => h('path', { key: k, d: 'M' + (216 + k * 8) + ' 52 Q' + (226 + k * 8) + ' 70 ' + (216 + k * 8) + ' 88', stroke: RED, strokeWidth: 4, fill: 'none' }))) : null,
        h('text', { x: 190, y: 112, textAnchor: 'middle', fontSize: 11, fontFamily: 'IBM Plex Mono', fontWeight: 700, fill: noche ? '#fff' : SINK }, on ? '¡SUENA!' : 'silencio'));
    }

    // ---------- Pregunta en vivo ----------
    function Vivo(p, q, preg, opts, correcta) {
      const mia = p.mis && p.mis[q], res = p.res && p.res[q];
      const conteo = opts.map((o, i) => res ? Object.values(res).filter(v => v.r === String(i)).length : 0), tot = res ? Object.keys(res).length : 0;
      return Card({ borderColor: BLUE, gap: 14 }, Row({ justifyContent: 'space-between' }, K('Pregunta en vivo', BLUE), p.docente ? K(tot + ' parejas respondieron', BLUE) : mia != null ? K('Respuesta enviada ✓', OKC) : null),
        H2(preg), Say(p, preg),
        D({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,220px),1fr))', gap: 10 }, ...opts.map((o, i) => {
          const sel = mia === String(i), mostrar = p.docente && p.ver, pc = tot ? Math.round(conteo[i] * 100 / tot) : 0, esOk = correcta != null && i === correcta && (p.ver || mia != null);
          return h('button', { key: i, onClick: () => { if (!p.docente && mia == null) p.onResp(q, String(i), correcta == null ? true : i === correcta); }, style: { position: 'relative', overflow: 'hidden', textAlign: 'left', padding: '14px 16px', fontFamily: 'inherit', fontWeight: 600, fontSize: 'clamp(15px,1.25vw,20px)', background: CARD, border: '3px solid ' + (esOk ? OKC : sel ? INK : LINE), cursor: p.docente || mia != null ? 'default' : 'pointer', color: INK } },
            mostrar ? h('div', { style: { position: 'absolute', left: 0, top: 0, bottom: 0, width: pc + '%', background: esOk ? 'rgba(127,224,160,.22)' : 'rgba(110,168,255,.2)' } }) : null,
            h('div', { style: { position: 'relative', display: 'flex', justifyContent: 'space-between', gap: 10 } }, h('span', null, o), mostrar ? h('span', { style: { fontFamily: MONO } }, conteo[i] + ' · ' + pc + '%') : sel ? h('span', null, '●') : null));
        })),
        !p.docente && mia != null && correcta != null ? T(mia === String(correcta) ? '¡Correcto! Esperen la explicación del docente.' : 'Respuesta enviada. Al final veremos juntos la correcta.', { color: MUTE, fontSize: 16 }) : null);
    }

    // ================= DIAPOSITIVAS =================
    // ===== 9no · Variables, constantes, tipos de datos y operadores =====
    const Code = (lines, st) => D(Object.assign({ background: '#070d12', color: '#e8f1f2', fontFamily: MONO, fontSize: 'clamp(14px,1.2vw,19px)', lineHeight: 1.6, padding: '14px 18px', overflowX: 'auto', whiteSpace: 'pre', border: '1px solid ' + LINE, borderRadius: 8 }, st || {}),
      ...lines.map((l, i) => { const parts = String(l).split('//'); return D({ display: 'flex', gap: 14, background: (st && st.hl === i) ? 'rgba(255,209,102,.18)' : 'transparent' }, h('span', { style: { color: '#6b7a83', minWidth: 20, textAlign: 'right', userSelect: 'none' } }, String(i + 1)), h('span', null, parts[0], parts.length > 1 ? h('span', { style: { color: '#7fe0a0' } }, '//' + parts.slice(1).join('//')) : null)); }));
    const Teo = (p, tit, lineas, ej, code) => Card({ borderColor: BLUE, background: 'rgba(110,168,255,.10)', gap: 10 }, D({ display: 'flex', gap: 16, alignItems: 'center' }, h(Icon, { k: ILUS[tit] || 'caja', s: 64, anim: true }), D({ display: 'flex', flexDirection: 'column', gap: 4 }, K('Aprende · 30 segundos', BLUE), H2(tit))), ...lineas.map((x, i) => D({ display: 'flex', gap: 10 }, D({ fontFamily: HEAD, color: BLUE, fontSize: 18 }, '›'), T(x))), code ? Code(code) : null, ej ? D({ borderTop: '2px solid #d5e1f7', paddingTop: 10, display: 'flex', flexDirection: 'column', gap: 4 }, K('En la vida real', TEAL), T(ej)) : null, Say(p, tit + '. ' + lineas.join(' ') + (ej ? ' En la vida real: ' + ej : '')));
    const TeoToggle = (p, args) => { const [v, setV] = useState(!p.intentos && !p.experto); return v ? D({ display: 'flex', flexDirection: 'column', gap: 8 }, Teo(p, ...args), Btn('Ocultar teoría', () => setV(false), { bg: CARD, c: BLUE, bd: BLUE, fs: 15, pad: '8px 14px' })) : Btn('Ver la teoría (no resta puntos)', () => setV(true), { bg: CARD, c: BLUE, bd: BLUE, fs: 15, pad: '8px 14px' }); };
    function Caja({ tipo, nombre, valor, cte, flash }) {
      return D({ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, minWidth: 120 },
        D({ fontFamily: MONO, fontSize: 13, fontWeight: 700, color: cte ? RED : BLUE, letterSpacing: '.08em' }, (cte ? 'const ' : '') + tipo),
        D({ width: 130, height: 86, border: '3px solid ' + (cte ? RED : BLUE), borderRadius: 8, color: INK, background: flash ? SELB : SUNK, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: HEAD, fontSize: 30, position: 'relative', transition: 'background .3s' }, String(valor), cte ? D({ position: 'absolute', right: 6, top: 4, fontFamily: MONO, fontSize: 11, color: RED, fontWeight: 700 }, 'FIJA') : null),
        D({ fontFamily: MONO, fontSize: 16, fontWeight: 700, background: BLUE, color: DARK, padding: '3px 10px' }, nombre));
    }
    function Ventilador({ on, temp }) {
      const [a, setA] = useState(0);
      useEffect(() => { if (!on) return; const t = setInterval(() => setA(x => (x + 24) % 360), 40); return () => clearInterval(t); }, [on]);
      const col = temp >= 30 ? '#e2553f' : temp >= 25 ? '#e7a03b' : '#3c8fd6';
      return h('svg', { viewBox: '0 0 220 170', style: { width: '100%', maxWidth: 260, height: 'auto', display: 'block' } },
        h('rect', { x: 0, y: 0, width: 220, height: 170, fill: '#eef1f2' }), h('rect', { x: 0, y: 140, width: 220, height: 30, fill: '#c9c3b6' }),
        h('rect', { x: 166, y: 30, width: 14, height: 100, rx: 7, fill: '#fff', stroke: SINK, strokeWidth: 2 }), h('rect', { x: 169, y: 130 - Math.max(4, Math.min(96, (temp - 10) * 3)), width: 8, height: Math.max(4, Math.min(96, (temp - 10) * 3)), fill: col }), h('circle', { cx: 173, cy: 134, r: 10, fill: col, stroke: SINK, strokeWidth: 2 }),
        h('text', { x: 173, y: 22, textAnchor: 'middle', fontSize: 14, fontWeight: 700, fill: SINK, fontFamily: 'monospace' }, temp + '°C'),
        h('rect', { x: 66, y: 98, width: 8, height: 44, fill: SINK }), h('rect', { x: 46, y: 140, width: 48, height: 6, fill: SINK }),
        h('g', { transform: 'translate(70,70) rotate(' + a + ')' }, ...[0, 120, 240].map(r => h('ellipse', { key: r, cx: 0, cy: -22, rx: 10, ry: 22, fill: on ? '#5fb3c9' : '#9aa5ab', transform: 'rotate(' + r + ')' })), h('circle', { r: 7, fill: SINK })),
        h('circle', { cx: 70, cy: 70, r: 46, fill: 'none', stroke: SINK, strokeWidth: 3 }));
    }
    // ===== FX 9no: neón, placa, monitor serial, escenas reales, íconos =====
    const GLOW = c => CLARO ? '0 2px 0 ' + c + '66' : '0 0 0 1px ' + c + '44, 0 0 24px ' + c + '30';
    const NE = (c, w) => ({ filter: 'drop-shadow(0 0 ' + (w || 4) + 'px ' + c + ')' });
    function Icon({ k, s, anim }) {
      const z = s || 56, st = { width: z, height: z, display: 'block', overflow: 'visible' }, g = (c, ...ch) => h('g', { fill: 'none', stroke: c, strokeWidth: 3, strokeLinecap: 'round', strokeLinejoin: 'round', style: NE(c, 3) }, ...ch);
      const A = n => anim ? { animation: n } : {};
      const m = {
        caja: () => g(BLUE, h('path', { d: 'M10 22 L32 12 L54 22 L54 46 L32 56 L10 46 Z' }), h('path', { d: 'M10 22 L32 32 L54 22 M32 32 L32 56' }), h('text', { x: 32, y: 10, textAnchor: 'middle', fontSize: 14, fill: BLUE, stroke: 'none', fontFamily: 'monospace', fontWeight: 700, style: A('c9float 1.6s ease-in-out infinite') }, '42')),
        candado: () => g(RED, h('rect', { x: 14, y: 28, width: 36, height: 26, rx: 4 }), h('path', { d: 'M22 28 V20 a10 10 0 0 1 20 0 V28', style: Object.assign({ transformOrigin: '42px 28px' }, A('c9lock 2.4s ease-in-out infinite')) }), h('circle', { cx: 32, cy: 40, r: 3 })),
        contador: () => g(TEAL, h('rect', { x: 8, y: 14, width: 48, height: 36, rx: 4 }), h('text', { x: 32, y: 40, textAnchor: 'middle', fontSize: 20, fill: TEAL, stroke: 'none', fontFamily: 'monospace', fontWeight: 700 }, '+1')),
        barras: () => g(AMB, ...[0, 1, 2].map(i => h('rect', { key: i, x: 8 + i * 17, y: 18, width: 14, height: 28, rx: 2 })), h('rect', { x: 8, y: 50, width: 8, height: 6, rx: 1, style: A('c9blink 1s steps(2) infinite') })),
        balanza: () => g(BLUE, h('path', { d: 'M32 12 V54 M20 54 H44' }), h('g', { style: Object.assign({ transformOrigin: '32px 16px' }, A('c9tilt 2.4s ease-in-out infinite')) }, h('path', { d: 'M10 16 H54 M10 16 L4 32 H18 Z M54 16 L48 32 H60 Z' }))),
        lupa: () => g(AMB, h('circle', { cx: 26, cy: 26, r: 15 }), h('path', { d: 'M37 37 L54 54' }), h('path', { d: 'M20 26 H32', style: A('c9blink 1.2s steps(2) infinite') })),
        puertas: () => g(AMB, h('rect', { x: 6, y: 14, width: 22, height: 40, rx: 2 }), h('rect', { x: 36, y: 14, width: 22, height: 40, rx: 2 }), h('text', { x: 32, y: 10, textAnchor: 'middle', fontSize: 12, fill: AMB, stroke: 'none', fontFamily: 'monospace', fontWeight: 700 }, '&& ||')),
        termo: () => g(RED, h('path', { d: 'M28 10 a4 4 0 0 1 8 0 V38 a10 10 0 1 1 -8 0 Z' }), h('circle', { cx: 32, cy: 46, r: 5, fill: RED, style: A('c9blink 1.4s ease-in-out infinite') })),
        lampara: () => g(AMB, h('path', { d: 'M20 30 a12 12 0 1 1 24 0 c0 6 -5 8 -5 14 H25 c0 -6 -5 -8 -5 -14 Z' }), h('path', { d: 'M26 50 H38 M28 56 H36' }), h('path', { d: 'M32 4 V0 M12 12 L9 9 M52 12 L55 9', style: A('c9blink 1s steps(2) infinite') })),
        pasos: () => g(TEAL, ...[0, 1, 2, 3].map(i => h('path', { key: i, d: 'M10 ' + (14 + i * 12) + ' H' + (30 + (i % 2) * 20), style: i === 1 ? { stroke: AMB } : {} })), h('path', { d: 'M4 26 l4 -2 v4 z', fill: AMB, stroke: AMB }))
      };
      return h('svg', { viewBox: '0 0 64 64', style: st }, (m[k] || m.caja)());
    }
    const ILUS = { 'Tipos de datos': 'caja', 'Variable o constante': 'candado', 'Actualizar una variable': 'contador', 'Operadores aritméticos': 'barras', 'Operadores relacionales': 'balanza', 'Errores comunes': 'lupa', 'Operadores lógicos': 'puertas', 'Seguir las variables': 'pasos' };
    function Placa({ pins, w }) {
      const PX = n => n[0] === 'A' ? { x: 168 + Number(n.slice(1)) * 18, y: 196, top: false } : { x: 290 - (Number(n.slice(1)) - 2) * 18, y: 70, top: true };
      return h('svg', { viewBox: '0 0 360 270', style: { width: '100%', maxWidth: w || 380, height: 'auto', display: 'block' } },
        h('rect', { x: 30, y: 58, width: 300, height: 150, rx: 12, fill: '#0b4f6c', stroke: '#5fd0e8', strokeWidth: 2, style: NE('#5fd0e8', 6) }),
        h('rect', { x: 18, y: 92, width: 34, height: 30, rx: 3, fill: '#9aa5ab' }), h('rect', { x: 18, y: 150, width: 26, height: 30, rx: 3, fill: '#222' }),
        h('rect', { x: 150, y: 120, width: 120, height: 30, rx: 3, fill: '#15191d', stroke: '#3a4b55' }), h('text', { x: 210, y: 140, textAnchor: 'middle', fontSize: 11, fill: '#9fb0ba', fontFamily: 'monospace' }, 'ATmega328P'),
        h('text', { x: 92, y: 140, textAnchor: 'middle', fontSize: 15, fontWeight: 700, fill: '#e8f1f2', fontFamily: 'sans-serif' }, 'ARDUINO'), h('text', { x: 92, y: 156, textAnchor: 'middle', fontSize: 11, fill: '#9fd8cf', fontFamily: 'monospace' }, 'UNO'),
        ...[...Array(12)].map((_, i) => h('rect', { key: 'd' + i, x: 286 - i * 18, y: 64, width: 8, height: 10, fill: '#111', stroke: '#555' })), ...[...Array(12)].map((_, i) => h('text', { key: 'dt' + i, x: 290 - i * 18, y: 88, textAnchor: 'middle', fontSize: 8, fill: '#cfe', fontFamily: 'monospace' }, String(i + 2))),
        ...[...Array(6)].map((_, i) => h('rect', { key: 'a' + i, x: 164 + i * 18, y: 192, width: 8, height: 10, fill: '#111', stroke: '#555' })), ...[...Array(6)].map((_, i) => h('text', { key: 'at' + i, x: 168 + i * 18, y: 186, textAnchor: 'middle', fontSize: 8, fill: '#cfe', fontFamily: 'monospace' }, 'A' + i)),
        h('circle', { cx: 300, cy: 100, r: 4, fill: (pins || []).some(p => p.on) ? '#7fe0a0' : '#2a4a3a', style: (pins || []).some(p => p.on) ? NE('#7fe0a0', 5) : {} }), h('text', { x: 300, y: 116, textAnchor: 'middle', fontSize: 7, fill: '#cfe', fontFamily: 'monospace' }, 'L'),
        ...(pins || []).map((p, i) => { const q = PX(p.pin), ey = q.top ? 22 : 248, ex = q.top ? 40 + i * 120 : 60 + i * 130, c = p.col || TEAL;
          return h('g', { key: 'w' + i }, h('path', { d: 'M' + (q.x) + ' ' + (q.top ? 64 : 202) + ' V' + (q.top ? 44 : 222) + ' H' + (ex + 40) + ' V' + ey, fill: 'none', stroke: p.on ? c : '#41525c', strokeWidth: 3, style: p.on ? Object.assign({ strokeDasharray: '6 5', animation: 'c9flow .6s linear infinite' }, NE(c, 4)) : {} }),
            h('rect', { x: ex, y: q.top ? 2 : 238, width: 80, height: 28, rx: 6, fill: '#0a1016', stroke: p.on ? c : '#41525c', strokeWidth: 2, style: p.on ? NE(c, 5) : {} }), h('text', { x: ex + 40, y: q.top ? 20 : 256, textAnchor: 'middle', fontSize: 10, fontWeight: 700, fill: p.on ? c : '#9fb0ba', fontFamily: 'monospace' }, p.name)); }));
    }
    function Serial({ lines, tit }) {
      return D({ background: '#04080b', border: '1px solid ' + TEAL, borderRadius: 8, boxShadow: GLOW(TEAL), display: 'flex', flexDirection: 'column', minWidth: 0 },
        D({ display: 'flex', justifyContent: 'space-between', padding: '6px 12px', borderBottom: '1px solid ' + LINE, fontFamily: MONO, fontSize: 12, color: MUTE, letterSpacing: '.08em' }, h('span', null, tit || 'MONITOR SERIAL'), h('span', null, '9600 baud')),
        D({ fontFamily: MONO, fontSize: 'clamp(13px,1.05vw,16px)', color: OKC, padding: '8px 12px', minHeight: 116, display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', gap: 2, textShadow: '0 0 6px rgba(127,224,160,.5)' },
          ...(lines || []).slice(-6).map((l, i, a) => D({ key: i + l, opacity: 0.45 + 0.55 * (i + 1) / a.length, whiteSpace: 'pre', overflow: 'hidden', textOverflow: 'ellipsis' }, '> ' + l)), (lines || []).length ? null : D({ color: MUTE }, '> esperando datos…')));
    }
    function useTick(ms) { const [t, setT] = useState(0); useEffect(() => { const i = setInterval(() => setT(x => x + 1), ms); return () => clearInterval(i); }, []); return t; }
    function Aula({ on, temp }) {
      const t = useTick(70), a = on ? t * 26 : 0, calor = temp >= 28, col = temp >= 30 ? RED : temp >= 25 ? AMB : BLUE, fy = Math.max(6, Math.min(80, (temp - 10) * 2.7));
      const alumno = (x, k) => { const ab = calor && !on, sw = ab ? Math.sin(t / 2 + k) * 18 : 0;
        return h('g', { key: x }, h('rect', { x: x - 16, y: 150, width: 32, height: 26, rx: 4, fill: '#3a5160' }), h('circle', { cx: x, cy: 136, r: 11, fill: '#d9b48f' }), h('rect', { x: x - 13, y: 147, width: 26, height: 18, rx: 6, fill: ['#6ea8ff', '#ff8fd0', '#3fd0b8'][k] }),
          ab ? h('g', { transform: 'translate(' + (x + 16) + ',134) rotate(' + sw + ')' }, h('path', { d: 'M0 0 L14 -10 L16 6 Z', fill: '#f0a726' })) : null, ab ? h('circle', { cx: x - 8, cy: 126 + (t % 10), r: 2.4, fill: '#8fd3ff' }) : null); };
      return h('svg', { viewBox: '0 0 320 190', style: { width: '100%', maxWidth: 360, height: 'auto', display: 'block' } },
        h('rect', { width: 320, height: 190, fill: calor && !on ? '#2a1a14' : '#101b24' }), h('rect', { x: 0, y: 176, width: 320, height: 14, fill: '#26343e' }), h('rect', { x: 18, y: 18, width: 110, height: 60, rx: 3, fill: '#0d2a22', stroke: '#2f6b4d', strokeWidth: 3 }), h('text', { x: 73, y: 52, textAnchor: 'middle', fontSize: 13, fill: '#bfe8d0', fontFamily: 'monospace' }, 'if (t > LIMITE)'),
        h('g', { transform: 'translate(220,52)' }, h('circle', { r: 36, fill: 'none', stroke: on ? TEAL : '#41525c', strokeWidth: 3, style: on ? NE(TEAL, 6) : {} }), h('g', { transform: 'rotate(' + a + ')' }, ...[0, 120, 240].map(r => h('ellipse', { key: r, cx: 0, cy: -17, rx: 8, ry: 17, fill: on ? '#5fd0e8' : '#55636c', transform: 'rotate(' + r + ')' }))), h('circle', { r: 5, fill: '#e8f1f2' })),
        on ? h('path', { d: 'M196 96 Q220 ' + (110 + (t % 6)) + ' 244 96', stroke: '#8fe3ff', strokeWidth: 2, fill: 'none', opacity: 0.6 }) : null,
        h('rect', { x: 284, y: 20, width: 14, height: 90, rx: 7, fill: '#0a1016', stroke: col, strokeWidth: 2, style: NE(col, 4) }), h('rect', { x: 287, y: 106 - fy, width: 8, height: fy, rx: 4, fill: col }), h('circle', { cx: 291, cy: 116, r: 9, fill: col, style: NE(col, 6) }), h('text', { x: 291, y: 14, textAnchor: 'middle', fontSize: 12, fontWeight: 700, fill: col, fontFamily: 'monospace' }, temp + '°C'),
        alumno(60, 0), alumno(130, 1), alumno(200, 2));
    }
    function Pasillo({ on, luz, mov }) {
      const t = useTick(60), noche = luz < 300, px = mov ? 40 + ((t * 3) % 240) : 250;
      const cielo = noche ? '#070d1c' : luz < 600 ? '#4a3a52' : '#6aa8d8';
      return h('svg', { viewBox: '0 0 320 190', style: { width: '100%', maxWidth: 360, height: 'auto', display: 'block' } },
        h('rect', { width: 320, height: 190, fill: noche ? '#0b1218' : '#2a3a46' }), h('rect', { x: 230, y: 20, width: 70, height: 60, fill: cielo, stroke: '#41525c', strokeWidth: 3 }), noche ? h('circle', { cx: 278, cy: 40, r: 8, fill: '#e8f1f2' }) : h('circle', { cx: 278, cy: 40, r: 10, fill: '#ffd84a' }),
        h('path', { d: 'M0 150 L320 150 L320 190 L0 190 Z', fill: '#1a252d' }), ...[30, 110, 190].map(x => h('rect', { key: x, x, y: 70, width: 34, height: 80, fill: '#24323c', stroke: '#3a5160', strokeWidth: 2 })), ...[30, 110, 190].map(x => h('text', { key: 't' + x, x: x + 17, y: 64, textAnchor: 'middle', fontSize: 9, fill: '#9fb0ba', fontFamily: 'monospace' }, x === 30 ? 'LAB' : x === 110 ? '9NO' : '10MO')),
        on ? h('polygon', { points: '150,22 230,150 70,150', fill: 'rgba(255,214,102,.22)' }) : null, h('rect', { x: 130, y: 8, width: 40, height: 10, rx: 3, fill: '#41525c' }), h('ellipse', { cx: 150, cy: 22, rx: 18, ry: 6, fill: on ? '#ffe27a' : '#55636c', style: on ? NE('#ffd166', 10) : {} }),
        h('rect', { x: 8, y: 30, width: 14, height: 10, rx: 2, fill: mov ? '#ff7b72' : '#41525c', style: mov ? NE('#ff7b72', 5) : {} }), h('text', { x: 15, y: 54, textAnchor: 'middle', fontSize: 8, fill: '#9fb0ba', fontFamily: 'monospace' }, 'PIR'),
        mov ? h('g', { transform: 'translate(' + px + ',0)' }, h('circle', { cx: 0, cy: 104, r: 8, fill: on || !noche ? '#d9b48f' : '#3a4048' }), h('rect', { x: -7, y: 112, width: 14, height: 22, rx: 5, fill: on || !noche ? '#6ea8ff' : '#2a3442' }), h('path', { d: 'M-4 134 L' + (-6 + Math.sin(t / 2) * 5) + ' 150 M4 134 L' + (6 - Math.sin(t / 2) * 5) + ' 150', stroke: on || !noche ? '#e8f1f2' : '#3a4048', strokeWidth: 3 })) : null,
        !on && noche ? h('rect', { width: 320, height: 190, fill: 'rgba(0,0,0,.35)' }) : null);
    }
    const SEG = { 0: 'abcdef', 1: 'bc', 2: 'abged', 3: 'abgcd', 4: 'fgbc', 5: 'afgcd', 6: 'afgedc', 7: 'abc', 8: 'abcdefg', 9: 'abcdfg', '-': 'g' };
    function Siete({ n, col }) {
      const s = String(n == null ? '--' : n).padStart(2, ' ').slice(-3), c = col || '#ff5d5d', W = 38;
      const seg = (k, x) => { const P = { a: [x + 6, 4, 26, 6], b: [x + 32, 8, 6, 26], c: [x + 32, 40, 6, 26], d: [x + 6, 66, 26, 6], e: [x, 40, 6, 26], f: [x, 8, 6, 26], g: [x + 6, 35, 26, 6] }[k]; return P; };
      return h('svg', { viewBox: '0 0 ' + (s.length * W + 8) + ' 76', style: { width: s.length * 54, height: 'auto', display: 'block', background: '#0a0505', borderRadius: 6, padding: 6 } }, ...s.split('').map((ch, i) => 'abcdefg'.split('').map(k => { const r = seg(k, 6 + i * W), lit = (SEG[ch] || '').includes(k); return h('rect', { key: i + k, x: r[0], y: r[1], width: r[2], height: r[3], rx: 2, fill: lit ? c : '#2a1414', style: lit ? NE(c, 4) : {} }); })));
    }
    function Barras({ a, b, op }) {
      if (op === '/' || op === '%') { const q = Math.trunc(a / b), r = a % b, show = Math.min(q, 12);
        return D({ display: 'flex', flexDirection: 'column', gap: 8, width: '100%' }, D({ display: 'flex', gap: 4, flexWrap: 'wrap', alignItems: 'center' },
          ...[...Array(show)].map((_, i) => D({ key: i, flex: '0 0 auto', width: Math.max(16, b / a * 260), height: 30, borderRadius: 4, background: op === '/' ? 'rgba(240,167,38,.25)' : OFF, border: '2px solid ' + (op === '/' ? AMB : '#41525c'), boxShadow: op === '/' ? GLOW(AMB) : 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: MONO, fontSize: 12, color: INK }, String(b))),
          q > show ? D({ fontFamily: MONO, color: MUTE }, '…') : null, r ? D({ width: Math.max(12, r / a * 260), height: 30, borderRadius: 4, background: op === '%' ? 'rgba(255,123,114,.28)' : OFF, border: '2px dashed ' + (op === '%' ? RED : '#41525c'), boxShadow: op === '%' ? GLOW(RED) : 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: MONO, fontSize: 12, color: INK }, String(r)) : null),
          T(op === '/' ? 'Caben ' + q + ' grupos completos de ' + b + ' → ' + a + ' / ' + b + ' = ' + q : 'Sobran ' + r + ' después de armar ' + q + ' grupos de ' + b + ' → ' + a + ' % ' + b + ' = ' + r, { fontSize: 16, color: op === '/' ? AMB : RED, fontWeight: 600 })); }
      const mx = Math.max(a + b, a, 1), bar = (v, c, lab, dash) => D({ width: Math.max(4, v / mx * 100) + '%', height: 26, borderRadius: 4, background: c + '33', border: '2px ' + (dash ? 'dashed ' : 'solid ') + c, display: 'flex', alignItems: 'center', paddingLeft: 8, fontFamily: MONO, fontSize: 12, color: INK, boxShadow: GLOW(c) }, lab);
      if (op === '*') { const r = Math.min(a, 12), c = Math.min(b, 12); return D({ display: 'flex', flexDirection: 'column', gap: 8 }, D({ display: 'grid', gridTemplateColumns: 'repeat(' + c + ',14px)', gap: 3 }, ...[...Array(r * c)].map((_, i) => D({ key: i, width: 14, height: 14, borderRadius: 3, background: TEAL, boxShadow: '0 0 6px ' + TEAL }))), T((a > 12 || b > 12 ? 'Vista parcial · ' : '') + a + ' filas × ' + b + ' columnas = ' + a * b, { fontSize: 16, color: TEAL, fontWeight: 600 })); }
      if (op === '+') return D({ display: 'flex', flexDirection: 'column', gap: 6, width: '100%' }, D({ display: 'flex', gap: 0, width: '100%' }, bar(a, BLUE, String(a)), bar(b, TEAL, String(b))), T(a + ' + ' + b + ' = ' + (a + b), { fontSize: 16, color: TEAL, fontWeight: 600 }));
      return D({ display: 'flex', flexDirection: 'column', gap: 6, width: '100%' }, D({ display: 'flex', width: '100%' }, bar(Math.max(0, a - b), BLUE, String(Math.max(0, a - b))), bar(Math.min(a, b), RED, '−' + b, true)), T(a + ' − ' + b + ' = ' + (a - b), { fontSize: 16, color: BLUE, fontWeight: 600 }));
    }
    function correrProg(lines) { const v = {}, ty = {}, out = [];
      lines.forEach(l => { const m = l.replace(/;.*$/, '').match(/^\s*(?:(const\s+)?(int|bool|float)\s+)?(\w+)\s*=\s*(.+)$/); if (!m) { out.push(Object.assign({}, v)); return; }
        if (m[2]) ty[m[3]] = m[2]; const ex = m[4].replace(/\b[a-zA-Z_]\w*\b/g, w => (w in v ? '(' + v[w] + ')' : w === 'true' || w === 'false' ? w : w));
        let r; try { r = Function('return (' + ex + ')')(); } catch (e) { r = '?'; } if (ty[m[3]] === 'int' && typeof r === 'number') r = Math.trunc(r); if (ty[m[3]] === 'bool') r = !!r; v[m[3]] = r; out.push(Object.assign({}, v)); });
      return out; }
    function Paso({ code }) {
      const tr = correrProg(code), [i, setI] = useState(-1), v = i >= 0 ? tr[i] : {};
      return D({ display: 'flex', flexDirection: 'column', gap: 10 }, Code(code, { hl: i }), Row({}, Btn(i < code.length - 1 ? '▶ Siguiente línea' : '✓ Fin', () => setI(Math.min(code.length - 1, i + 1)), { bg: TEAL, dis: i >= code.length - 1, fs: 15, pad: '8px 14px' }), Btn('Reiniciar', () => setI(-1), { bg: CARD, c: INK, fs: 15, pad: '8px 14px' })),
        Row({ gap: 12 }, ...Object.keys(v).map(k => h(Caja, { key: k, tipo: typeof v[k] === 'boolean' ? 'bool' : 'int', nombre: k, valor: String(v[k]), flash: true }))));
    }
    // ===== 3ro BGU · Evaluación de fuentes y uso ético: confiabilidad, derechos de autor y licencias (DRP.13.1) =====
    Object.assign(ILUS, { 'Señales de confiabilidad': 'lupa', 'Evaluar una fuente': 'balanza', 'Dominios y autoría': 'caja', 'Licencias Creative Commons': 'candado', 'Usos permitidos': 'puertas', 'Cita, paráfrasis y plagio': 'pasos', 'Contrastar fuentes': 'balanza', 'Matriz de valoración': 'barras' });
    const WEB = (f, st) => D(Object.assign({ background: '#ffffff', color: SINK, border: '2px solid ' + LINE, borderRadius: 10, overflow: 'hidden', display: 'flex', flexDirection: 'column', minWidth: 0 }, st || {}),
      D({ background: '#e8edf0', padding: '7px 12px', display: 'flex', gap: 8, alignItems: 'center', borderBottom: '1px solid #cfd8dd' }, D({ display: 'flex', gap: 5 }, ...['#ff5f57', '#febc2e', '#28c840'].map(c => D({ key: c, width: 10, height: 10, borderRadius: 5, background: c }))), D({ flex: 1, background: '#fff', borderRadius: 999, padding: '3px 12px', fontFamily: MONO, fontSize: 13, color: '#3a454c', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }, f.url)),
      D({ padding: '14px 16px', display: 'flex', flexDirection: 'column', gap: 8 }, D({ fontFamily: HEAD, fontSize: 'clamp(17px,1.5vw,24px)', lineHeight: 1.15, color: SINK }, f.tit),
        D({ fontSize: 14, color: '#4a5760', display: 'flex', flexWrap: 'wrap', gap: '4px 14px' }, h('span', null, f.autor || 'Autor: no indicado'), h('span', null, f.fecha || 'Sin fecha'), f.inst ? h('span', null, f.inst) : null),
        f.txt ? D({ fontSize: 15, lineHeight: 1.45, color: '#22292e' }, f.txt) : null,
        D({ display: 'flex', flexWrap: 'wrap', gap: 8, fontSize: 13, fontFamily: MONO, color: '#4a5760' }, f.refs != null ? h('span', null, f.refs ? '📚 ' + f.refs + ' referencias' : 'Sin referencias') : null, f.lic ? h('span', null, '© ' + f.lic) : null, f.likes ? h('span', null, '♥ ' + f.likes) : null)));
    const Medidor = (v, lab) => { const c = v >= 70 ? OKC : v >= 40 ? AMB : RED; return D({ display: 'flex', flexDirection: 'column', gap: 6, width: '100%' }, Row({ justifyContent: 'space-between' }, K(lab || 'Confianza', INK), D({ fontFamily: HEAD, fontSize: 'clamp(22px,2.2vw,36px)', color: c }, v + ' %')), D({ height: 22, borderRadius: 11, background: OFF, overflow: 'hidden', border: '2px solid ' + LINE }, D({ width: v + '%', height: '100%', background: c, transition: 'width .4s' }))); };
    const S = [];
    S.push({ id: 'portada', t: 'Propósito', r: p => Grid(420,
      D({ display: 'flex', flexDirection: 'column', gap: 22 }, K('Robótica · 3ro BGU · Competencias académicas digitales'), H1('¿Puedo confiar en esto? Fuentes confiables y uso ético'), T('En la universidad, cada afirmación de un trabajo debe estar respaldada por una fuente confiable y usada con respeto a su autor. Hoy aprenderemos a decidir qué fuentes usar y bajo qué condiciones.'), p.codigo ? Card({ borderColor: TEAL }, K('Código de la sesión', TEAL), D({ fontFamily: HEAD, fontSize: 'clamp(40px,5vw,80px)', color: TEAL, letterSpacing: '.08em' }, p.codigo)) : null),
      Card({ gap: 16 }, K('Hoy aprenderemos a…', TEAL), T(['Evaluar fuentes digitales con ', B('criterios de confiabilidad'), ' y reconocer ', B('autoría, derechos de autor y licencias'), ' para seleccionar información de forma ética.']), K('Sabremos que lo logramos si…', TEAL),
        ...['Evaluamos una fuente con criterios explícitos.', 'Reconocemos qué permite cada licencia.', 'Justificamos por qué usamos o descartamos una fuente.'].map((x, i) => D({ display: 'flex', gap: 12, borderTop: '2px solid ' + LINE, paddingTop: 12 }, D({ fontFamily: HEAD, fontSize: 22, color: TEAL }, String(i + 1)), T(x))), Say(p, 'Hoy aprenderemos a evaluar fuentes digitales con criterios de confiabilidad y a reconocer autoría, derechos de autor y licencias.'))) });
    S.push({ id: 'acuerdos', t: 'Acuerdos y roles', r: p => D({ display: 'flex', flexDirection: 'column', gap: 22 }, H1('Cómo trabajamos hoy'),
      Grid(260, ...[['Mano arriba', 'Cuando el docente levanta la mano, silencio y manos fuera del teclado.'], ['Pensamiento crítico', 'Toda opinión se justifica con un criterio, no con «me parece».'], ['Integridad', 'Trabajamos solo en esta página: sin buscadores ni IA durante los retos.']].map(([a, b]) => Card({}, H2(a), T(b)))),
      Card({ borderColor: TEAL }, K('Roles en la pareja · cambian en cada reto', TEAL), Grid(300, D({ display: 'flex', flexDirection: 'column', gap: 6 }, H2('Analista'), T('Revisa la fuente y propone una decisión.')), D({ display: 'flex', flexDirection: 'column', gap: 6 }, H2('Crítico/a'), T('Pide la evidencia: «¿con qué criterio?».'))))) });
    const FA = { url: 'misterios-ocultos.blogspot.com', tit: '¡Lo que los científicos NO quieren que sepas sobre el agua!', autor: 'Autor: «Admin»', fecha: 'Publicado: 2015', txt: 'Beber agua fría después de comer causa graves enfermedades. Compártelo antes de que lo borren.', refs: 0, likes: '48 300' };
    const FB = { url: 'revistas.uees.edu.ec/salud/article/1127', tit: 'Hidratación y temperatura del agua: revisión de estudios', autor: 'Dra. Ana Torres · Fac. de Medicina', fecha: 'Marzo 2024', inst: 'Universidad · revista revisada por pares', txt: 'No se encontró evidencia de que la temperatura del agua afecte la digestión en personas sanas (12 estudios revisados).', refs: 38, lic: 'CC BY 4.0', likes: '210' };
    S.push({ id: 'motiv', t: 'Motivación', r: p => D({ display: 'flex', flexDirection: 'column', gap: 18 }, K('Piensen un momento'), H1('Dos páginas, la misma pregunta. ¿Cuál usarían?'), Grid(380, WEB(FA), WEB(FB)), Vivo(p, 'motiv', 'Para un trabajo universitario usarían…', ['La A: tiene muchos más likes', 'La B: tiene autora, fecha, institución y referencias', 'Las dos por igual', 'Ninguna'], 1)) });
    const CRIT = [['autor', 'Autoría', '¿Quién lo escribió? ¿Tiene nombre y formación en el tema?', 'Dra. Ana Torres, Facultad de Medicina'], ['fecha', 'Fecha', '¿Es actual para el tema? En ciencia y tecnología, mejor de los últimos 5 años.', 'Marzo 2024'], ['inst', 'Institución', '¿Lo respalda una universidad, revista u organismo serio?', 'Revista universitaria revisada por pares'], ['refs', 'Referencias', '¿Indica de dónde salen los datos? ¿Se pueden verificar?', '38 referencias'], ['prop', 'Propósito', '¿Busca informar, o vender, convencer o asustar?', 'Informar · no vende nada'], ['evid', 'Evidencia', '¿Hay datos, estudios o pruebas, o solo opiniones?', '12 estudios revisados']];
    function Senales(p) {
      const [on, setOn] = useState({ autor: false, fecha: false, inst: false, refs: false, prop: false, evid: false }), [likes, setLikes] = useState(500);
      const v = Math.round(Object.values(on).filter(Boolean).length / 6 * 100);
      const f = { url: on.inst ? 'repositorio.ucuenca.edu.ec/estudio-agua' : 'agua-saludable-tips.com', tit: on.prop ? 'Temperatura del agua y digestión: lo que dicen los estudios' : '¡El secreto del agua que te cambiará la vida! Compra nuestro filtro', autor: on.autor ? 'Ing. Luis Pérez, Msc. en Nutrición' : null, fecha: on.fecha ? 'Junio 2025' : null, inst: on.inst ? 'Universidad de Cuenca' : null, txt: on.evid ? 'Según 12 estudios con 3 400 participantes, no hay diferencia significativa…' : 'Todo el mundo sabe que el agua fría es mala. ¡Créenos!', refs: on.refs ? 24 : 0, likes: likes.toLocaleString('es') };
      return Grid(380, D({ display: 'flex', flexDirection: 'column', gap: 14 }, K('Construcción · señales de confiabilidad'), H1('El medidor de confianza'), T('Activen cada criterio y miren cómo cambia la página y el medidor. Después muevan los «likes».'),
        Row({}, ...CRIT.map(([k, n]) => Chip((on[k] ? '✓ ' : '') + n, on[k], () => setOn(Object.assign({}, on, { [k]: !on[k] })), TEAL))), Slider('Likes de la página', likes, 0, 100000, setLikes), Medidor(v),
        T(likes > 20000 && v < 50 ? 'Muchos likes, poca confianza: la popularidad NO es un criterio académico.' : 'La confianza solo sube con criterios: autoría, fecha, institución, referencias, propósito y evidencia.', { color: likes > 20000 && v < 50 ? RED : MUTE, fontWeight: 600 }), Say(p, 'La confianza solo sube con criterios: autoría, fecha, institución, referencias, propósito y evidencia. La popularidad no es un criterio académico.')),
        WEB(f));
    }
    S.push({ id: 'senales', t: 'Señales de confiabilidad', r: p => h(Senales, p) });
    function Criterios(p) {
      const [s, setS] = useState(0), C = CRIT[s];
      return Grid(380, D({ display: 'flex', flexDirection: 'column', gap: 14 }, K('Construcción · la matriz de evaluación'), H1('Seis preguntas para cualquier fuente'), Grid(160, ...CRIT.map(([k, n], i) => h('button', { key: k, onClick: () => setS(i), style: { padding: '14px 12px', borderRadius: 10, border: '2px solid ' + (s === i ? TEAL : LINE), background: s === i ? TEAL : CARD, color: s === i ? DARK : INK, fontFamily: HEAD, fontSize: 'clamp(16px,1.4vw,22px)', cursor: 'pointer', textAlign: 'left' } }, (i + 1) + '. ' + n)))),
        Card({ borderColor: TEAL, gap: 12 }, h(Icon, { k: ['caja', 'contador', 'puertas', 'pasos', 'balanza', 'barras'][s], s: 64, anim: true }), H2(C[1]), T(C[2]), Card({ background: SUNK, gap: 4 }, K('En la fuente B', TEAL), T(C[3])), Say(p, C[1] + '. ' + C[2])));
    }
    S.push({ id: 'criterios', t: 'Criterios', r: p => h(Criterios, p) });
    const AF = [['El agua fría no afecta la digestión en personas sanas.', 'ambas', 'Las dos fuentes científicas coinciden.'], ['Se revisaron 12 estudios.', 'una', 'Solo la fuente 1 da ese dato: hay que verificarlo.'], ['Hay que beber 2 litros exactos al día.', 'nada', 'Ninguna de las dos lo dice: no tiene sustento.'], ['El agua tibia mejora la memoria.', 'contra', 'La fuente 2 dice que no hay evidencia: se contradicen.']];
    function Contrasta(p) {
      const [v, setV] = useState({}), lab = { ambas: ['Coinciden las dos', OKC], una: ['Solo una lo dice', AMB], nada: ['Sin sustento', RED], contra: ['Se contradicen', RED] };
      return D({ display: 'flex', flexDirection: 'column', gap: 16 }, K('Construcción · contrastar'), H1('Una fuente sola no basta'), T('Toquen cada afirmación del trabajo de un compañero y descubran qué tan respaldada está.'),
        Grid(340, WEB({ url: 'revistas.uees.edu.ec/salud/1127', tit: 'Fuente 1 · Revisión de 12 estudios', autor: 'Dra. Ana Torres', fecha: '2024', txt: 'La temperatura del agua no afecta la digestión en personas sanas. Se revisaron 12 estudios.', refs: 38 }), WEB({ url: 'who.int/es/hidratacion', tit: 'Fuente 2 · Organización Mundial de la Salud', autor: 'OMS', fecha: '2023', txt: 'No hay evidencia de efectos de la temperatura del agua en la digestión ni en la memoria.', refs: 15 })),
        Grid(300, ...AF.map(([a, k, ex], i) => h('button', { key: i, onClick: () => setV(Object.assign({}, v, { [i]: true })), style: { textAlign: 'left', padding: '14px 16px', borderRadius: 10, background: CARD, color: INK, border: '2px solid ' + (v[i] ? lab[k][1] : LINE), cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: 6 } }, D({ fontWeight: 700, fontSize: 'clamp(15px,1.3vw,20px)' }, '«' + a + '»'), v[i] ? D({ color: lab[k][1], fontWeight: 700 }, lab[k][0] + ' · ' + ex) : D({ color: MUTE, fontSize: 14 }, 'Toquen para revisar')))));
    }
    S.push({ id: 'contrasta', t: 'Contrastar fuentes', r: p => h(Contrasta, p) });
    const licTxt = (nc, nd, sa) => 'CC BY' + (nc ? '-NC' : '') + (nd ? '-ND' : sa ? '-SA' : '') + ' 4.0';
    const usos = (nc, nd, sa) => [['Copiar y compartir', true], ['Modificar o adaptar', !nd], ['Usar para ganar dinero', !nc], ['Compartir con la misma licencia', sa && !nd ? 'obligatorio' : 'opcional'], ['Citar al autor', 'siempre']];
    function Licencias(p) {
      const [nc, setNc] = useState(false), [nd, setNd] = useState(false), [sa, setSa] = useState(false);
      const btn = (t, d, on, set, col) => h('button', { onClick: set, style: { padding: '12px 14px', borderRadius: 10, border: '2px solid ' + (on ? col : LINE), background: on ? col : CARD, color: on ? DARK : INK, cursor: 'pointer', textAlign: 'left', display: 'flex', flexDirection: 'column', gap: 4, minWidth: 0 } }, D({ fontFamily: HEAD, fontSize: 'clamp(18px,1.6vw,26px)' }, t), D({ fontSize: 14, fontWeight: 600 }, d));
      return Grid(380, D({ display: 'flex', flexDirection: 'column', gap: 14 }, K('Construcción · derechos de autor y licencias'), H1('Armen una licencia Creative Commons'), T(['Todo lo que alguien crea tiene ', B('derechos de autor'), '. Con una licencia CC, el autor dice qué permite hacer. ', B('BY'), ' (citar al autor) va siempre.']),
        Grid(200, btn('BY', 'Citar al autor · siempre', true, () => {}, TEAL), btn('NC', 'No comercial', nc, () => setNc(!nc), AMB), btn('ND', 'Sin obras derivadas', nd, () => { setNd(!nd); if (!nd) setSa(false); }, RED), btn('SA', 'Compartir igual', sa, () => { setSa(!sa); if (!sa) setNd(false); }, BLUE)),
        T('ND y SA no se combinan: si no se puede modificar, no hay obra nueva que compartir.', { color: MUTE, fontSize: 16 }), Say(p, 'BY: citar al autor. NC: no comercial. ND: sin obras derivadas. SA: compartir con la misma licencia.')),
        Card({ gap: 12, borderColor: TEAL }, D({ fontFamily: HEAD, fontSize: 'clamp(30px,3.4vw,56px)', color: TEAL }, licTxt(nc, nd, sa)), ...usos(nc, nd, sa).map(([u, ok]) => Row({ justifyContent: 'space-between', borderTop: '2px solid ' + LINE, paddingTop: 10 }, T(u, { fontWeight: 600 }), D({ fontFamily: HEAD, fontSize: 'clamp(16px,1.4vw,22px)', color: ok === true || ok === 'siempre' || ok === 'obligatorio' ? OKC : ok === false ? RED : MUTE }, ok === true ? 'SÍ' : ok === false ? 'NO' : ok.toUpperCase()))),
          T('Ejemplo real: Wikipedia usa CC BY-SA. Pueden usar y modificar sus textos, citándola y compartiendo con la misma licencia.', { color: MUTE, fontSize: 16 })));
    }
    S.push({ id: 'licencias', t: 'Licencias', r: p => h(Licencias, p) });
    const ORIG = 'La inteligencia artificial puede apoyar el aprendizaje, pero sus respuestas deben verificarse con fuentes confiables.';
    const VERS = [['Cita textual', '«La inteligencia artificial puede apoyar el aprendizaje, pero sus respuestas deben verificarse con fuentes confiables» (Torres, 2024, p. 12).', OKC, 'Palabras exactas, entre comillas, con autor, año y página.'], ['Paráfrasis', 'Según Torres (2024), la IA es útil para aprender siempre que comprobemos lo que responde con fuentes serias.', BLUE, 'Idea del autor con palabras propias, y se cita igual.'], ['Plagio', 'La inteligencia artificial puede apoyar el aprendizaje, pero sus respuestas deben verificarse con fuentes confiables.', RED, 'Copiado sin comillas ni autor: es presentar como propio el trabajo de otro.']];
    function Plagio(p) {
      const [s, setS] = useState(0), V = VERS[s];
      return Grid(380, D({ display: 'flex', flexDirection: 'column', gap: 14 }, K('Construcción · uso ético'), H1('Cita, paráfrasis o plagio'), Card({ background: SUNK, gap: 6 }, K('Texto original · Torres (2024), p. 12'), T('«' + ORIG + '»')), Row({}, ...VERS.map(([n, , c], i) => Chip(n, s === i, () => setS(i), c))), Say(p, V[0] + '. ' + V[3])),
        Card({ gap: 12, borderColor: V[2] }, K(V[0], V[2]), T(V[1], { fontStyle: s === 2 ? 'normal' : 'italic' }), T(V[3], { fontWeight: 700, color: V[2] }), s === 2 ? T('Copiar de una IA o de internet sin citar también es plagio.', { color: RED }) : null));
    }
    S.push({ id: 'plagio', t: 'Cita y plagio', r: p => h(Plagio, p) });
    function Resuelto(p) {
      const F = { url: 'eltiempo-noticias.net/tecnologia/robots', tit: 'Los robots reemplazarán al 90 % de los trabajos en 2027', autor: 'Redacción', fecha: '2019', txt: 'Expertos aseguran que casi todos los trabajos desaparecerán. Lee más y suscríbete por $4,99.', refs: 0, likes: '120 000' };
      const P = [['Autoría', 0, '«Redacción»: no hay un autor identificable.'], ['Fecha', 1, '2019: algo antigua para un tema de tecnología.'], ['Institución', 0, 'Un sitio .net de noticias sin respaldo académico.'], ['Referencias', 0, 'Dice «expertos aseguran», pero no cita a ninguno.'], ['Propósito', 0, 'Pide suscribirse: busca vender, no informar.'], ['Evidencia', 0, 'Un número llamativo (90 %) sin estudio que lo respalde.']];
      const [i, setI] = useState(-1), tot = P.slice(0, i + 1).reduce((a, x) => a + x[1], 0);
      return Grid(380, D({ display: 'flex', flexDirection: 'column', gap: 14 }, K('Ejercicio resuelto · paso a paso'), H1('Evaluemos juntos una fuente'), WEB(F), Row({}, Btn(i < P.length - 1 ? '▶ Siguiente criterio' : '✓ Decisión final', () => setI(Math.min(P.length, i + 1)), { bg: TEAL, dis: i >= P.length }), Btn('Reiniciar', () => setI(-1), { bg: CARD, c: INK }))),
        Card({ gap: 10 }, K('Matriz de valoración · 0 no cumple · 1 parcial · 2 cumple'), ...P.map(([n, v, ex], k) => D({ key: k, display: 'flex', flexDirection: 'column', gap: 4, borderTop: '2px solid ' + LINE, paddingTop: 8, opacity: k <= i ? 1 : 0.35 }, Row({ justifyContent: 'space-between' }, T(n, { fontWeight: 700 }), D({ fontFamily: HEAD, fontSize: 22, color: v === 2 ? OKC : v ? AMB : RED }, k <= i ? v + ' / 2' : '?')), k <= i ? T(ex, { fontSize: 16, color: MUTE }) : null)),
          i >= P.length ? Card({ borderColor: RED, gap: 6 }, D({ fontFamily: HEAD, fontSize: 'clamp(22px,2.2vw,34px)', color: RED }, 'Total ' + tot + ' / 12 → DESCARTAR'), T('Justificación: no tiene autor, ni referencias, ni evidencia, y su propósito es vender. Que tenga 120 000 likes no la hace confiable.')) : D({ fontFamily: HEAD, fontSize: 24 }, 'Total parcial: ' + tot)));
    }
    S.push({ id: 'resuelto', t: 'Ejercicio resuelto', r: p => h(Resuelto, p) });
    function Relampago(p) {
      const [s, setS] = useState(30); useEffect(() => { const i = setInterval(() => setS(x => Math.max(0, x - 1)), 1000); return () => clearInterval(i); }, []);
      const c = s > 10 ? AMB : RED;
      return Grid(380, D({ display: 'flex', flexDirection: 'column', gap: 16 }, K('Reto relámpago · 30 segundos', AMB), H1('Encontraron esta imagen en internet para su informe'), Card({ gap: 6 }, T('Foto de un robot · Autor: María Gómez · Licencia: CC BY-NC-ND 4.0'), T('Quieren recortarla y ponerle texto encima.', { color: MUTE })), D({ fontFamily: HEAD, fontSize: 'clamp(48px,6vw,96px)', color: c, lineHeight: 1 }, s ? s + ' s' : '¡Tiempo!')),
        Vivo(p, 'relampago', '¿Pueden hacerlo?', ['Sí, citando a la autora', 'No: ND no permite modificarla', 'Sí, porque está en internet', 'Sí, si no la venden'], 1));
    }
    S.push({ id: 'relampago', t: 'Reto relámpago', r: p => h(Relampago, p) });
    S.push({ id: 'retos', t: 'Modo reto', r: p => D({ display: 'flex', flexDirection: 'column', gap: 20 }, K('Ahora ustedes'), H1('Modo reto: elijan sus retos y completen 6'), T('Cada reto tiene ejemplo resuelto, mini prueba y pistas en 3 niveles. Elijan la ruta: Básico, Normal o Experto (da medalla).'),
      Grid(240, ...[['Nivel 1', 'Señales de confiabilidad · ¿Usar o descartar? · Detective de dominios'], ['Nivel 2', 'Arma la licencia · ¿Puedo usarlo? · Cita, paráfrasis o plagio'], ['Nivel 3', 'Contrasta fuentes · Matriz de valoración'], ['Minijuegos', 'Carrera · Atrapa la fuente dudosa · Simón · Conecta licencias']].map(([a, b]) => Card({}, H2(a), T(b))))) });

    // ---------- RETOS ----------
    function Reto(p, body, nombre, enun, teo) { return D({ display: 'flex', flexDirection: 'column', gap: 16 }, Row({ justifyContent: 'space-between' }, K('Reto · ' + nombre, TEAL), K('Intentos ' + (p.intentos || 0), MUTE)), H1(enun.t, { fontSize: 'clamp(26px,2.8vw,46px)' }), T(enun.d), Say(p, enun.t + '. ' + enun.d), teo ? h(TeoBox, { p, a: teo }) : null, body); }
    function TeoBox({ p, a }) { return TeoToggle(p, a); }
    const ayuda = (p, txt) => p.sinAyuda ? null : p.verPista ? Card({ borderColor: AMB }, K('Pista', AMB), T(txt)) : Btn('Ver una pista (−1 punto)', p.pedirPista, { bg: CARD, c: AMB, bd: AMB });
    const Clasif = (p, items, opts, cols, onOk, okTxt, malTxt, id) => { const [r, setR] = useState({}), listo = items.every((_, i) => r[i] != null);
      return D({ display: 'flex', flexDirection: 'column', gap: 14 }, Grid(320, ...items.map((it, i) => Card({ gap: 10, borderColor: r[i] != null ? cols[r[i]] : LINE }, typeof it[0] === 'string' ? T(it[0], { fontWeight: 700 }) : it[0], Row({}, ...opts.map((o, k) => Chip(o, r[i] === k, () => setR(Object.assign({}, r, { [i]: k })), cols[k])))))),
        Row({}, Btn('Comprobar', () => { const mal = items.findIndex((x, i) => r[i] !== x[1]); p.check(mal < 0, mal < 0 ? okTxt : malTxt(items[mal]), id); }, { dis: !listo, bg: TEAL }), ayuda(p, onOk))); };
    const SEN = [['El autor indica su nombre y su formación', 0, 'saber quién escribe permite juzgar si sabe del tema'], ['El artículo tiene 80 000 «me gusta»', 1, 'la popularidad no prueba que algo sea verdad'], ['Cita estudios y se pueden revisar', 0, 'las referencias permiten verificar'], ['El título dice «¡Lo que nadie te cuenta!»', 1, 'los títulos exagerados buscan clics, no informar'], ['Lo publica una universidad o revista científica', 0, 'hay revisión de expertos detrás'], ['En la misma página venden un producto milagroso', 1, 'si busca vender, puede exagerar'], ['No tiene fecha de publicación', 1, 'no sabemos si la información está vigente'], ['Presenta datos con su fuente', 0, 'la evidencia verificable da confianza']];
    function RSen(p) { const items = p.adaptado ? SEN.slice(0, 5) : SEN;
      return Reto(p, Clasif(p, items, ['Da confianza', 'Señal de alerta'], [OKC, RED], 'Pregunten: ¿esto me ayuda a saber si la información es verdadera?', '¡Perfecto! Ya distinguen los criterios académicos de las trampas de popularidad.', x => '«' + x[0] + '»: ' + x[2] + '.', 'senal'),
        'Señales', { t: '¿Da confianza o es una alerta?', d: 'Clasifiquen cada característica de una página web.' }, ['Señales de confiabilidad', ['Dan confianza: autor identificable, fecha, institución, referencias, evidencia.', 'Son alertas: títulos exagerados, sin autor, sin fecha, propósito de vender.', 'Los likes y las visitas NO son un criterio.'], 'Antes de compartir una noticia en WhatsApp, revisar quién la publica evita difundir información falsa.']); }
    const FUEN = [[{ url: 'scielo.org/articulo/robotica-educativa', tit: 'Impacto de la robótica educativa en el pensamiento lógico', autor: 'M. Castro, U. Central del Ecuador', fecha: '2023', refs: 41, lic: 'CC BY 4.0' }, 0, 'Tiene autora, institución, fecha reciente y referencias.'], [{ url: 'robots-asombrosos.wordpress.com', tit: '10 robots que te volarán la cabeza', autor: null, fecha: null, refs: 0, likes: '15 000' }, 1, 'No tiene autor, ni fecha, ni referencias: sirve para entretener, no para citar.'], [{ url: 'inec.gob.ec/estadisticas/tic-2024', tit: 'Tecnologías de la información en hogares · 2024', autor: 'Instituto Nacional de Estadística y Censos', fecha: '2024', refs: 6, inst: 'Gobierno del Ecuador' }, 0, 'Es una institución oficial con datos actuales.'], [{ url: 'tiktok.com/@techboy/video/88', tit: 'La IA ya piensa sola (video viral)', autor: '@techboy', fecha: '2024', refs: 0, likes: '2,1 M' }, 1, 'Es una opinión sin evidencia, aunque sea muy vista.']];
    function RFuen(p) { const items = (p.adaptado ? FUEN.slice(0, 3) : FUEN).map(([f, a, ex]) => [WEB(f), a, ex]);
      return Reto(p, Clasif(p, items, ['Usar', 'Descartar'], [OKC, RED], 'Revisen autor, fecha, institución y referencias de cada una.', '¡Bien! Usaron criterios, no apariencias.', x => 'Revisen otra vez. ' + x[2], 'fuente'),
        'Fuentes', { t: '¿Usar o descartar?', d: 'Para un informe sobre robótica en la educación, decidan qué fuentes usarían.' }, ['Evaluar una fuente', ['Revisen las seis preguntas: autoría, fecha, institución, referencias, propósito y evidencia.', 'Una fuente puede ser interesante y aun así no servir para un trabajo académico.'], 'Las universidades piden en las tesis solo fuentes que se puedan verificar.']); }
    const URLS = [['www.espol.edu.ec/investigacion', 0, '.edu indica una institución educativa'], ['www.salud.gob.ec/boletin', 1, '.gob indica una entidad del gobierno'], ['ciencia-facil.blogspot.com', 2, 'blogspot es un blog personal: cualquiera puede publicar'], ['www.e1comercio.com.ec', 3, 'imita a «elcomercio» cambiando la l por un 1'], ['scholar.google.com/…', 4, 'Google Académico es un buscador de artículos científicos'], ['www.bbc-noticias24.info', 3, 'imita a la BBC con un dominio extraño']];
    function RUrl(p) { const items = (p.adaptado ? URLS.slice(0, 4) : URLS).map(([u, a, ex]) => [D({ fontFamily: MONO, fontSize: 'clamp(15px,1.3vw,20px)', fontWeight: 700, background: SUNK, padding: '8px 12px', borderRadius: 999 }, u), a, ex]);
      return Reto(p, Clasif(p, items, ['Universidad', 'Gobierno', 'Blog personal', 'Sitio que imita', 'Buscador académico'], [BLUE, TEAL, AMB, RED, OKC], 'Lean el final del dominio (.edu, .gob) y busquen letras cambiadas.', '¡Excelentes detectives! El dominio es la primera pista de quién publica.', x => 'Revisen: ' + x[2] + '.', 'url'),
        'Dominios', { t: 'Detective de dominios', d: '¿Quién publica cada dirección?' }, ['Dominios y autoría', ['.edu y .edu.ec: instituciones educativas.', '.gob y .gob.ec: gobierno.', 'Cuidado con los sitios que imitan a medios conocidos cambiando una letra.'], 'Muchas estafas por correo usan direcciones casi iguales a las de los bancos.']); }
    const NEED = [['María quiere que usen su foto citándola, que la modifiquen, pero que nadie gane dinero con ella.', [true, false, false], 'CC BY-NC 4.0'], ['Un profesor quiere que copien su guía, pero que no la cambien.', [false, true, false], 'CC BY-ND 4.0'], ['Un grupo de estudiantes quiere que todo lo que se cree a partir de su app se comparta con la misma licencia.', [false, false, true], 'CC BY-SA 4.0']];
    function RLic(p) { const items = p.adaptado ? NEED.slice(0, 2) : NEED, [r, setR] = useState(items.map(() => [false, false, false])), [ix, setIx] = useState(0), cur = r[ix];
      const tog = k => { const n = r.map(x => x.slice()); n[ix][k] = !n[ix][k]; if (k === 1 && n[ix][1]) n[ix][2] = false; if (k === 2 && n[ix][2]) n[ix][1] = false; setR(n); };
      return Reto(p, D({ display: 'flex', flexDirection: 'column', gap: 14 }, Row({}, ...items.map((_, i) => Chip('Caso ' + (i + 1), ix === i, () => setIx(i), BLUE))), Card({ gap: 10 }, T(items[ix][0], { fontWeight: 700 }), Row({}, Chip('BY ✓', true, () => {}, TEAL), Chip('NC · no comercial', cur[0], () => tog(0), AMB), Chip('ND · sin cambios', cur[1], () => tog(1), RED), Chip('SA · compartir igual', cur[2], () => tog(2), BLUE)), D({ fontFamily: HEAD, fontSize: 'clamp(24px,2.6vw,40px)', color: TEAL }, licTxt(cur[0], cur[1], cur[2]))),
        Row({}, Btn('Comprobar los ' + items.length + ' casos', () => { const mal = items.findIndex((x, i) => x[1].some((v, k) => v !== r[i][k])); p.check(mal < 0, mal < 0 ? '¡Licencias correctas! Así protegen su propio trabajo en la universidad.' : 'Revisen el caso ' + (mal + 1) + ': la licencia correcta es ' + (p.verPista ? items[mal][2] : 'otra. Lean qué permite y qué no.'), 'licencia'); }, { bg: TEAL }), ayuda(p, 'NC = no ganar dinero. ND = no modificar. SA = compartir con la misma licencia.'))),
        'Licencias', { t: 'Arma la licencia', d: 'Elijan la licencia Creative Commons que cumple lo que quiere cada autor.' }, ['Licencias Creative Commons', ['BY: siempre citar al autor.', 'NC: no se puede usar para ganar dinero.', 'ND: no se puede modificar.', 'SA: lo nuevo se comparte con la misma licencia.'], 'Muchas fotos de Wikimedia Commons tienen licencia CC: se pueden usar en un informe citando al autor.']); }
    const USE = [['CC BY 4.0 · Usar un gráfico en su informe, citando al autor', 0, 'BY permite todo, siempre citando'], ['CC BY-NC 4.0 · Imprimir camisetas con la imagen y venderlas', 1, 'NC prohíbe el uso comercial'], ['CC BY-ND 4.0 · Traducir el texto y publicarlo', 1, 'traducir es modificar, y ND no lo permite'], ['© Todos los derechos reservados · Copiar el capítulo completo en su página web', 1, 'se necesita permiso del autor'], ['Dominio público · Usar un cuadro antiguo en una presentación', 0, 'en dominio público el uso es libre (igual es buena práctica citar)'], ['CC BY-SA 4.0 · Mejorar un texto de Wikipedia y compartirlo con la misma licencia', 0, 'SA lo permite si se comparte igual']];
    function RUse(p) { const items = p.adaptado ? USE.slice(0, 4) : USE;
      return Reto(p, Clasif(p, items, ['Sí, se puede', 'No se puede'], [OKC, RED], 'Lean cada letra de la licencia: NC, ND y SA ponen condiciones.', '¡Correcto! Usar contenidos con respeto también es parte de la integridad académica.', x => '«' + x[0] + '»: ' + x[2] + '.', 'uso'),
        'Usos', { t: '¿Puedo usarlo?', d: 'Decidan si cada uso está permitido por la licencia.' }, ['Usos permitidos', ['© sin licencia: hace falta permiso del autor.', 'CC: se puede usar según sus letras, siempre citando.', 'Dominio público: uso libre.'], 'YouTube retira videos que usan música con © sin permiso.']); }
    const CIT = [['«La robótica fortalece el pensamiento lógico» (Castro, 2023, p. 4).', 0, 'palabras exactas entre comillas con autor, año y página'], ['Castro (2023) explica que trabajar con robots ayuda a razonar paso a paso.', 1, 'idea del autor con otras palabras, y citada'], ['La robótica fortalece el pensamiento lógico de los estudiantes.', 2, 'son las palabras del autor sin comillas ni cita'], ['Creo que la robótica debería ser obligatoria en todos los colegios.', 3, 'es la postura propia del estudiante'], ['Según la UNESCO (2024), la IA debe usarse con supervisión humana.', 1, 'es una idea atribuida, con palabras propias'], ['Texto pegado de ChatGPT sin indicarlo.', 2, 'presentar texto generado por IA como propio también es plagio']];
    function RCit(p) { const items = p.adaptado ? CIT.slice(0, 4) : CIT;
      return Reto(p, Clasif(p, items, ['Cita textual', 'Paráfrasis', 'Plagio', 'Opinión propia'], [OKC, BLUE, RED, AMB], 'Busquen: comillas, nombre del autor, año. ¿Hay palabras copiadas sin citar?', '¡Muy bien! Distinguir esto evita el plagio en la universidad.', x => '«' + x[0] + '»: ' + x[2] + '.', 'cita'),
        'Cita', { t: 'Cita, paráfrasis o plagio', d: 'Clasifiquen cada fragmento de un informe.' }, ['Cita, paráfrasis y plagio', ['Cita textual: palabras exactas entre comillas + (Autor, año, página).', 'Paráfrasis: la idea con palabras propias + (Autor, año).', 'Plagio: usar palabras o ideas ajenas sin citar, también si vienen de una IA.'], 'Las universidades usan programas que detectan plagio comparando millones de textos.']); }
    const CON = [['Los estudiantes con robótica mejoraron 18 % en lógica.', 0, 'las dos fuentes dan el mismo dato'], ['La robótica mejora las notas de todas las materias.', 2, 'ninguna fuente lo dice'], ['El estudio se hizo con 400 estudiantes.', 1, 'solo la fuente A da ese dato'], ['La mejora apareció después de 6 meses.', 3, 'A dice 6 meses y B dice 1 año']];
    function RCon(p) { const items = p.adaptado ? CON.slice(0, 3) : CON;
      return Reto(p, D({ display: 'flex', flexDirection: 'column', gap: 14 }, Grid(340, WEB({ url: 'revista.ups.edu.ec/2024/robotica', tit: 'Fuente A · Robótica y lógica en colegios', autor: 'P. Ruiz', fecha: '2024', txt: 'Con 400 estudiantes, la mejora en lógica fue de 18 % después de 6 meses.', refs: 22 }), WEB({ url: 'educacion.gob.ec/informe-robotica', tit: 'Fuente B · Informe del Ministerio', autor: 'MINEDUC', fecha: '2024', txt: 'Los estudiantes de robótica mejoraron 18 % en lógica tras un año de clases.', refs: 9 })),
        Clasif(p, items, ['Coinciden', 'Solo una lo dice', 'Sin sustento', 'Se contradicen'], [OKC, AMB, RED, BLUE], 'Busquen cada dato en la fuente A y en la B.', '¡Excelente análisis! Contrastar evita repetir errores de una sola fuente.', x => '«' + x[0] + '»: ' + x[2] + '.', 'contraste')),
        'Contrastar', { t: 'Contrasta las fuentes', d: 'Revisen cada afirmación del informe de un compañero comparándola con las dos fuentes.' }, ['Contrastar fuentes', ['Si dos fuentes confiables coinciden, la afirmación es más sólida.', 'Si solo una lo dice, hay que verificarlo.', 'Si ninguna lo dice, no se puede escribir como un hecho.'], 'Los periodistas confirman una noticia con al menos dos fuentes independientes.']); }
    const MAT = { url: 'investigacion.ucuenca.edu.ec/paper/ia-aula', tit: 'Uso de inteligencia artificial en el aula: estudio con 250 docentes', autor: 'Dr. J. Vélez · Universidad de Cuenca', fecha: '2017', txt: 'Encuesta a 250 docentes. Concluye que la IA ahorra tiempo de planificación. Financiado por una empresa que vende software educativo.', refs: 31, lic: 'CC BY-NC 4.0' };
    const MCR = [['Autoría', 2, 'autor con nombre y universidad'], ['Fecha', 1, '2017 es antiguo para un tema de IA'], ['Institución', 2, 'universidad reconocida'], ['Referencias', 2, '31 referencias'], ['Propósito', 1, 'lo financia una empresa interesada: posible sesgo'], ['Evidencia', 2, 'encuesta con 250 docentes']];
    function RMat(p) { const items = p.adaptado ? MCR.filter((_, i) => i !== 4) : MCR, [v, setV] = useState({}), [dec, setDec] = useState(null), listo = items.every((_, i) => v[i] != null) && dec != null;
      const tot = items.reduce((a, _, i) => a + (v[i] || 0), 0), max = items.length * 2;
      return Reto(p, Grid(340, WEB(MAT), D({ display: 'flex', flexDirection: 'column', gap: 10 }, ...items.map(([n], i) => Row({ justifyContent: 'space-between', borderTop: '2px solid ' + LINE, paddingTop: 8 }, T(n, { fontWeight: 700 }), Row({ gap: 6 }, ...[0, 1, 2].map(k => Chip(String(k), v[i] === k, () => setV(Object.assign({}, v, { [i]: k })), k === 2 ? OKC : k ? AMB : RED))))),
        D({ fontFamily: HEAD, fontSize: 24 }, 'Total: ' + tot + ' / ' + max), K('Decisión'), Row({}, Chip('Usar con precaución, contrastando', dec === 0, () => setDec(0), AMB), Chip('Usar sin problema', dec === 1, () => setDec(1), OKC), Chip('Descartar', dec === 2, () => setDec(2), RED)),
        Row({}, Btn('Comprobar', () => { const mal = items.findIndex((x, i) => Math.abs((v[i] || 0) - x[1]) > (p.ruta === 'basico' ? 1 : 0)); if (mal >= 0) { p.check(false, 'Revisen «' + items[mal][0] + '»: ' + items[mal][2] + '.', 'matriz'); return; } p.check(dec === 0, dec === 0 ? 'Correcto: es una buena fuente, pero antigua y con posible conflicto de interés. Se usa contrastándola con otra más reciente.' : 'La valoración está bien, pero la decisión no. ¿Qué hacer con una fuente buena pero con fecha antigua y posible sesgo?', 'matriz'); }, { dis: !listo, bg: TEAL }), ayuda(p, '2 = cumple, 1 = cumple a medias, 0 = no cumple. Fíjense en la fecha y en quién financia el estudio.')))),
        'Matriz', { t: 'Matriz de valoración', d: 'Valoren la fuente en cada criterio (0, 1 o 2) y decidan qué hacer con ella.' }, ['Matriz de valoración', ['Cada criterio se valora: 0 no cumple, 1 parcial, 2 cumple.', 'La suma ayuda a decidir, pero hay que justificar.', 'Una fuente buena con un punto débil se usa con precaución y se contrasta.'], 'Los comités de revisión de las revistas científicas usan rúbricas parecidas.']); }
    const RETOS = [
      { id: 'senal', n: 'Señales de confiabilidad', ic: h(Icon, { k: 'lupa', s: 44 }), C: RSen, ad: true, nivel: 1 },
      { id: 'fuente', n: '¿Usar o descartar?', ic: h(Icon, { k: 'balanza', s: 44 }), C: RFuen, ad: true, nivel: 1 },
      { id: 'url', n: 'Detective de dominios', ic: h(Icon, { k: 'caja', s: 44 }), C: RUrl, ad: true, nivel: 1 },
      { id: 'licencia', n: 'Arma la licencia', ic: h(Icon, { k: 'candado', s: 44 }), C: RLic, ad: true, nivel: 2 },
      { id: 'uso', n: '¿Puedo usarlo?', ic: h(Icon, { k: 'puertas', s: 44 }), C: RUse, ad: false, nivel: 2 },
      { id: 'cita', n: 'Cita, paráfrasis o plagio', ic: h(Icon, { k: 'pasos', s: 44 }), C: RCit, ad: false, nivel: 2 },
      { id: 'contraste', n: 'Contrasta las fuentes', ic: h(Icon, { k: 'balanza', s: 44 }), C: RCon, ad: false, nivel: 3 },
      { id: 'matriz', n: 'Matriz de valoración', ic: h(Icon, { k: 'barras', s: 44 }), C: RMat, ad: false, nivel: 3 }];
    const X = {
      senal: { ej: { t: 'Así se revisa una página', pasos: ['Miren quién la escribe: «Admin» no es un autor identificable.', 'Miren la fecha: 2015 puede estar desactualizado.', 'Busquen referencias: si no hay, no se puede verificar.', 'Los likes no cuentan: millones de personas pueden estar equivocadas.'] }, mini: ['¿Cuál de estos es un criterio académico?', ['Número de likes', 'Referencias verificables', 'Diseño bonito', 'Que sea viral'], 1, 'Las referencias permiten verificar la información.'], pistas: ['¿Esto ayuda a saber si es verdad?', 'Autor, fecha, institución, referencias y evidencia dan confianza.', 'Alertas: likes, título exagerado, vender productos, sin fecha.'] },
      fuente: { ej: { t: 'Así se decide', pasos: ['Fuente: artículo en scielo.org con autora y universidad.', 'Fecha 2023 y 41 referencias.', 'Propósito: informar; tiene evidencia.', 'Decisión: USAR. Un video viral sin evidencia: DESCARTAR.'] }, mini: ['Un video con 2 millones de vistas y sin fuentes es…', ['Confiable', 'No confiable para un trabajo académico'], 1, 'Las vistas no reemplazan la evidencia.'], pistas: ['Revisen autor, fecha y referencias.', 'Las instituciones oficiales y revistas académicas suelen ser confiables.', 'Usar: SciELO e INEC. Descartar: blog sin autor y video viral.'] },
      url: { ej: { t: 'Así se lee una dirección', pasos: ['Lean el final: .edu.ec → institución educativa.', '.gob.ec → gobierno.', 'blogspot, wordpress → blog personal.', 'Comparen letra por letra: e1comercio ≠ elcomercio.'] }, mini: ['¿Quién publica en salud.gob.ec?', ['Una universidad', 'El gobierno', 'Un blog'], 1, '.gob indica una entidad de gobierno.'], pistas: ['Lean la parte final del dominio.', '.edu universidad · .gob gobierno · blogspot blog.', 'e1comercio y bbc-noticias24 imitan a medios conocidos.'] },
      licencia: { ej: { t: 'Así se arma una licencia', pasos: ['Siempre empieza con BY: citar al autor.', '¿Prohíbe ganar dinero? → agregar NC.', '¿Prohíbe modificar? → agregar ND.', '¿Exige compartir igual? → agregar SA.'] }, mini: ['NC significa…', ['No citar', 'No comercial', 'Nuevo contenido'], 1, 'NC = no comercial.'], pistas: ['Lean qué prohíbe cada autor.', 'No vender = NC. No modificar = ND. Compartir igual = SA.', 'Caso 1: BY-NC · Caso 2: BY-ND · Caso 3: BY-SA.'] },
      uso: { ej: { t: 'Así se decide si un uso está permitido', pasos: ['Lean la licencia: CC BY-ND.', '¿Qué quieren hacer? Traducir el texto.', 'Traducir es modificar, y ND lo prohíbe.', 'Decisión: no se puede.'] }, mini: ['Con © «todos los derechos reservados» se necesita…', ['Nada', 'Permiso del autor', 'Solo citar'], 1, 'Sin licencia abierta, hay que pedir permiso.'], pistas: ['¿Qué letras tiene la licencia?', 'NC: vender no. ND: modificar no. ©: pedir permiso.', 'Sí: BY, dominio público, BY-SA. No: NC vendiendo, ND traduciendo, © copiando.'] },
      cita: { ej: { t: 'Así se distingue', pasos: ['¿Está entre comillas con (Autor, año, página)? → cita textual.', '¿Es la idea del autor con otras palabras y citada? → paráfrasis.', '¿Son palabras ajenas sin citar? → plagio.', '¿Es lo que yo pienso? → opinión propia.'] }, mini: ['Copiar un texto de una IA sin indicarlo es…', ['Paráfrasis', 'Plagio', 'Cita'], 1, 'Presentar como propio un texto ajeno es plagio.'], pistas: ['Busquen comillas y nombres de autores.', 'Sin comillas ni autor, con palabras ajenas: plagio.', '1 cita · 2 paráfrasis · 3 plagio · 4 opinión · 5 paráfrasis · 6 plagio.'] },
      contraste: { ej: { t: 'Así se contrasta', pasos: ['Afirmación: «mejoraron 18 %».', 'Fuente A: 18 %. Fuente B: 18 %. → coinciden.', 'Afirmación: «después de 6 meses».', 'A dice 6 meses, B dice 1 año → se contradicen.'] }, mini: ['Si solo una fuente da un dato, hay que…', ['Escribirlo como hecho', 'Verificarlo', 'Ignorar las fuentes'], 1, 'Un dato de una sola fuente se verifica.'], pistas: ['Busquen cada dato en A y en B.', 'Si ninguna lo dice: sin sustento.', '18 %: coinciden · todas las materias: sin sustento · 400: solo una · 6 meses: se contradicen.'] },
      matriz: { ej: { t: 'Así se valora un criterio', pasos: ['Autoría: autor con nombre y universidad → 2.', 'Fecha: 2017 en un tema de IA → 1 (algo antigua).', 'Propósito: lo financia una empresa interesada → 1.', 'Total alto con puntos débiles → usar con precaución y contrastar.'] }, mini: ['Una fuente buena pero antigua se…', ['Descarta siempre', 'Usa contrastándola', 'Usa sin revisar'], 1, 'Se usa con precaución y se contrasta con fuentes recientes.'], pistas: ['2 cumple · 1 a medias · 0 no cumple.', 'La fecha y el financiamiento son los puntos débiles.', '2 · 1 · 2 · 2 · 1 · 2 y decisión: usar con precaución.'] }
    };
    RETOS.forEach(r => Object.assign(r, X[r.id] || {}));
    const JG = window.CLASE_JUEGOS ? window.CLASE_JUEGOS.make(React, { D, T, K, B, Card, Btn, Row, Code, Grid, H1, MONO, HEAD, c: { INK, MUTE, LINE, TEAL, AMB, RED, BLUE, OKC, CARD, SUNK, OFF } }) : null;
    if (JG) RETOS.push(
      { id: 'j_carrera', n: 'Carrera de la investigación', ic: h(Icon, { k: 'contador', s: 44 }), ad: true, nivel: 'JUEGO', juego: true, pistas: ['Todo empieza con una pregunta.', 'Antes de usar una fuente, se evalúa y se contrasta.', 'Pregunta → palabras clave → buscar → evaluar → contrastar → licencia → citar.'], C: p => h(JG.Carrera, Object.assign({ data: { tit: 'Carrera de la investigación', txt: 'Ordenen los pasos para usar una fuente en un trabajo académico.', lineas: ['Definir la pregunta de investigación', 'Elegir palabras clave', 'Buscar en Google Académico o repositorios', 'Revisar autor, fecha e institución', 'Contrastar con otra fuente', 'Revisar la licencia de uso', 'Citar y registrar la referencia'], corto: ['Definir la pregunta', 'Buscar fuentes', 'Evaluar la fuente', 'Citarla'], ok: 'Ese es el proceso de una investigación seria.' } }, p)) },
      { id: 'j_bug', n: 'Atrapa la fuente dudosa', ic: h(Icon, { k: 'lupa', s: 44 }), ad: true, nivel: 'JUEGO', juego: true, pistas: ['Busquen señales de alerta.', 'Sin autor, títulos exagerados, dominios raros.', 'Las .edu, .gob y revistas con autor son confiables.'], C: p => h(JG.Bug, Object.assign({ data: { tit: 'Atrapa la fuente dudosa', txt: 'Caen fuentes. Toquen SOLO las poco confiables.', ejemplo: 'Ejemplo de fuente dudosa: «¡Increíble! La IA te hará millonario» · sin autor', lineas: [['scielo.org · M. Castro · 2023', false], ['inec.gob.ec · Estadísticas 2024', false], ['who.int · OMS · 2023', false], ['revista.ups.edu.ec · P. Ruiz', false], ['scholar.google.com · artículo citado 120 veces', false], ['«¡Lo que no te dicen!» · sin autor', true, 'título exagerado y sin autor'], ['e1comercio.com.ec', true, 'imita a un medio conocido'], ['Video viral · 3 M vistas · sin fuentes', true, 'popularidad no es evidencia'], ['Blog · sin fecha · vende un curso', true, 'sin fecha y con propósito de vender'], ['Cadena de WhatsApp «reenvía a 10»', true, 'sin autor ni fuente']], ok: 'Ya detectan las fuentes dudosas a simple vista.' } }, p)) },
      { id: 'j_simon', n: 'Simón de los criterios', ic: h(Icon, { k: 'lampara', s: 44 }), ad: true, nivel: 'JUEGO', juego: true, pistas: ['Digan los criterios en voz alta.', 'Cada luz es un paso de la revisión.', 'Elijan la lista con el mismo orden.'], C: p => h(JG.Simon, Object.assign({ data: { tit: 'Simón de los criterios', txt: 'Memoricen el orden de revisión, repítanlo y luego elijan la lista de cotejo que lo sigue.', pads: [{ t: 'AUTOR', c: '#ff5d5d' }, { t: 'FECHA', c: '#3fd07a' }, { t: 'FUENTE', c: '#4d9bff' }, { t: 'EVIDENCIA', c: '#ffd166' }], programa: s => s.map((v, i) => (i + 1) + '. Revisar ' + ['el autor', 'la fecha', 'la institución', 'la evidencia'][v]) } }, p)) },
      { id: 'j_circuito', n: 'Conecta la licencia', ic: h(Icon, { k: 'candado', s: 44 }), ad: true, nivel: 'JUEGO', juego: true, izq: 'Licencia', pistas: ['Cada letra es una condición.', 'NC: no vender · ND: no modificar · ©: pedir permiso.', 'BY→todo citando · NC→sin vender · ND→sin modificar · ©→permiso · dominio público→libre.'], C: p => h(JG.Circuito, Object.assign({ data: { tit: 'Conecta cada licencia con lo que permite', txt: 'Toquen una licencia y luego lo que permite hacer.', der: 'Lo que permite', pares: [['CC BY', 'Modificar y vender, citando', 'BY solo pide citar al autor.'], ['CC BY-NC', 'Modificar, pero sin vender', 'NC prohíbe el uso comercial.'], ['CC BY-ND', 'Compartir, pero sin modificar', 'ND prohíbe las obras derivadas.'], ['© Todos los derechos', 'Necesito permiso del autor', 'Sin licencia abierta hay que pedir permiso.'], ['Dominio público', 'Uso libre', 'Ya no tiene derechos de autor vigentes.']], corto: 3, ok: '¡Licencias conectadas!' } }, p)) }
    );
    const GLOS = [['Fuente confiable', 'Información con autor, fecha, institución, referencias y evidencia.', 'Artículo de una revista universitaria.', 'balanza'], ['Autoría', 'Quién escribió el contenido y qué formación tiene.', 'Dra. Ana Torres, Medicina.', 'caja'], ['Referencias', 'Lista de fuentes que usó el autor; permiten verificar.', '38 referencias al final.', 'pasos'], ['Revisión por pares', 'Otros expertos revisan el artículo antes de publicarlo.', 'Revistas científicas.', 'lupa'], ['Derechos de autor', 'Protección legal de lo que una persona crea.', '© 2024 María Gómez.', 'candado'], ['Creative Commons', 'Licencias que dicen qué se permite hacer con una obra.', 'CC BY-NC-SA 4.0', 'candado'], ['Dominio público', 'Obras sin derechos vigentes: uso libre.', 'Cuadros de hace más de 100 años.', 'caja'], ['Cita textual', 'Palabras exactas entre comillas con (Autor, año, página).', '«…» (Torres, 2024, p. 12).', 'pasos'], ['Paráfrasis', 'La idea de otro con palabras propias, citando.', 'Según Torres (2024)…', 'pasos'], ['Plagio', 'Usar palabras o ideas ajenas sin citar, incluida la IA.', 'Copiar y pegar sin comillas.', 'lupa']];
    const TICKET = [['¿Cuál NO es un criterio de confiabilidad?', ['La autoría', 'Los likes', 'Las referencias'], 1], ['CC BY-ND permite…', ['Modificar la obra', 'Compartirla sin cambios', 'Venderla modificada'], 1], ['Copiar un texto de una IA sin indicarlo es…', ['Paráfrasis', 'Plagio', 'Cita textual'], 1]];
    const ESTR = ['Revisamos los seis criterios uno por uno', 'Usamos el ejemplo resuelto', 'Comparamos las fuentes entre sí', 'Nos pedimos la evidencia el uno al otro', 'Pedimos pistas'];
    const LOGROS = [['Evalúo fuentes con criterios explícitos de confiabilidad.', ['senal', 'fuente', 'url', 'j_bug', 'j_simon']], ['Reconozco autoría, derechos de autor y licencias.', ['licencia', 'uso', 'j_circuito']], ['Distingo cita, paráfrasis y plagio.', ['cita']], ['Contrasto fuentes y justifico mi selección.', ['contraste', 'matriz', 'j_carrera']]];
    const META = { q: '¿Qué criterio cambió su idea sobre una fuente que parecía confiable?', o: ['La autoría', 'La fecha', 'Las referencias', 'El propósito (vender, asustar)', 'La evidencia'] };
    make.c = { S, RETOS, META, Flujo, GLOS, TICKET, ESTR, LOGROS, Icon, curso: '3BGU', titulo: 'Fuentes confiables y uso ético' };
    return make.c;
  }
  window.CLASE3 = { make };
})();
