// 3ro BGU · Misión investigador: temas, simulador de Google Scholar, tabla con validación, rúbrica, presentación y panel docente.
(function () {
  const TEMAS = [
    ['redes', 'Redes sociales y salud mental', '¿Cómo influye el uso de redes sociales en la ansiedad y la autoestima de los adolescentes?', ['redes sociales adolescentes ansiedad', '"social media" adolescents "mental health"']],
    ['ia', 'IA y estudiantes', '¿Qué efectos tiene el uso de ChatGPT en el aprendizaje y la integridad académica?', ['ChatGPT estudiantes aprendizaje', 'ChatGPT students "academic integrity"']],
    ['juegos', 'Videojuegos y el cerebro', '¿Los videojuegos mejoran o empeoran la atención y la memoria?', ['videojuegos habilidades cognitivas', '"video games" "cognitive skills" adolescents']],
    ['sueno', 'Pantallas, sueño y notas', '¿Cómo afecta el uso de pantallas en la noche al sueño y al rendimiento escolar?', ['pantallas sueño rendimiento académico', '"screen time" sleep "academic performance"']],
    ['clima', 'Cambio climático en Ecuador', '¿Cómo está afectando el cambio climático a la agricultura del Ecuador?', ['cambio climático agricultura Ecuador', '"climate change" agriculture Ecuador']],
    ['energia', 'Energía solar en Latinoamérica', '¿Es viable la energía solar para los hogares de Latinoamérica?', ['energía solar hogares Latinoamérica', '"solar energy" households "Latin America"']],
    ['ciber', 'Ciberacoso', '¿Qué factores aumentan el ciberacoso entre jóvenes y cómo se previene?', ['ciberacoso adolescentes prevención', 'cyberbullying adolescents prevention']],
    ['comida', 'Comida ultraprocesada', '¿Qué relación hay entre los alimentos ultraprocesados y la salud de los jóvenes?', ['alimentos ultraprocesados adolescentes salud', '"ultra-processed food" adolescents health']],
    ['deporte', 'Deporte y rendimiento escolar', '¿La actividad física mejora el rendimiento académico?', ['actividad física rendimiento académico', '"physical activity" "academic achievement"']],
    ['musica', 'Música y concentración', '¿Escuchar música al estudiar ayuda o distrae?', ['música concentración estudio', 'music concentration studying']],
    ['fake', 'Noticias falsas', '¿Por qué los jóvenes creen y comparten noticias falsas?', ['noticias falsas jóvenes redes', 'misinformation youth "social media"']],
    ['carrera', 'Elegir una carrera', '¿Qué factores influyen en la elección de carrera universitaria?', ['elección de carrera universitaria factores', '"career choice" "high school students" factors']]];
  const CRIT = ['Autoría', 'Fecha', 'Institución', 'Referencias', 'Propósito', 'Evidencia'];
  const CAMPOS = [['titulo', 'Título del artículo', 'Uso de redes sociales y ansiedad en adolescentes ecuatorianos'], ['autores', 'Autor(es)', 'Torres, A. y Vélez, J.'], ['anio', 'Año', '2023'], ['revista', 'Revista o fuente', 'Revista Ecuatoriana de Psicología'], ['citas', '«Citado por» (número)', '45'], ['enlace', 'Enlace', 'https://revistas.uees.edu.ec/…'], ['apa', 'Cita APA (botón «Citar»)', 'Torres, A., & Vélez, J. (2023). Uso de redes sociales… Revista Ecuatoriana de Psicología, 12(2), 33-48.'], ['acceso', 'Acceso', '']];
  const SIM = [
    { t: 'Redes sociales y ansiedad en adolescentes: revisión sistemática', a: 'M Castro, L Ruiz', r: 'Revista de Psicología Clínica', y: 2022, c: 184, pdf: true, k: 'redes sociales ansiedad adolescentes' },
    { t: 'El uso de Instagram y la autoestima en estudiantes de secundaria', a: 'P Andrade', r: 'Educación y Sociedad', y: 2016, c: 412, pdf: false, k: 'redes sociales autoestima adolescentes' },
    { t: 'Redes sociales, ansiedad y sueño en adolescentes ecuatorianos', a: 'A Torres, J Vélez', r: 'Revista Ecuatoriana de Psicología', y: 2023, c: 45, pdf: true, k: 'redes sociales ansiedad adolescentes' },
    { t: '¿Las redes sociales causan ansiedad? Mitos y evidencia', a: 'Blog Vida Sana', r: 'vidasana.blogspot.com', y: 2021, c: 0, pdf: false, k: 'redes sociales ansiedad' },
    { t: 'Adolescentes y redes sociales: un estudio longitudinal de ansiedad', a: 'S Morales, D Paz', r: 'Psicología y Salud', y: 2021, c: 97, pdf: true, k: 'redes sociales ansiedad adolescentes' },
    { t: 'Tecnología y jóvenes en el siglo XXI', a: 'R Gómez', r: 'Editorial Andina', y: 2012, c: 230, pdf: false, k: 'tecnología jóvenes redes' },
    { t: 'Ansiedad social y uso problemático de redes sociales', a: 'C León', r: 'Anales de Psicología', y: 2024, c: 18, pdf: true, k: 'redes sociales ansiedad' }];
  const norm = s => String(s || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();
  const vacio = () => ({ titulo: '', autores: '', anio: '', revista: '', citas: '', enlace: '', apa: '', acceso: '', m: [null, null, null, null, null, null], por: '' });
  function avisos(a) {
    const w = [], y = Number(a.anio), now = new Date().getFullYear();
    if (a.anio && (!/^\d{4}$/.test(a.anio) || y > now)) w.push(['err', 'El año debe tener 4 cifras y no ser futuro.']);
    else if (y && y < 2020) w.push(['warn', 'Es de ' + y + ': ¿sigue siendo actual para su tema? Busquen con el filtro «Desde 2020».']);
    if (a.enlace && !/^https?:\/\/\S+\.\S+/.test(a.enlace)) w.push(['err', 'El enlace debe empezar con https:// y ser una dirección completa.']);
    else if (/google\.[a-z.]+\/(search|scholar\?)/.test(a.enlace)) w.push(['err', 'Ese es el enlace de la búsqueda, no del artículo. Abran el artículo y copien su dirección.']);
    if (a.apa && !/\(\s*\d{4}[a-z]?\s*\)/.test(a.apa)) w.push(['err', 'La cita APA debe tener el año entre paréntesis, por ejemplo (2023).']);
    if (a.apa && a.autores && !norm(a.apa).includes(norm(a.autores).split(' ')[0])) w.push(['warn', 'La cita no parece incluir al primer autor.']);
    if (a.citas !== '' && !/^\d+$/.test(a.citas)) w.push(['err', '«Citado por» debe ser un número (0 si no aparece).']);
    else if (a.citas !== '' && Number(a.citas) === 0) w.push(['warn', 'Nadie lo ha citado todavía: revisen bien la fuente.']);
    if (/blogspot|wordpress|wikipedia|youtube|tiktok|facebook/.test(a.enlace + ' ' + a.revista)) w.push(['warn', 'Parece un blog, red social o enciclopedia: no es un artículo académico.']);
    if (a.por && a.por.trim().length < 20) w.push(['warn', 'Expliquen un poco más por qué lo eligen (una oración completa).']);
    return w;
  }
  const completo = a => CAMPOS.every(([k]) => String(a[k] || '').trim()) && a.m.every(v => v != null) && a.por.trim().length >= 20;
  function evaluar(arts, min) {
    const ok = arts.filter(completo), n = ok.length, base = Math.max(min, n) || 1, sinErr = ok.filter(a => !avisos(a).some(w => w[0] === 'err'));
    const tit = {}; let dup = 0; ok.forEach(a => { const k = norm(a.titulo); if (tit[k]) dup++; tit[k] = 1; });
    const R = [
      ['Cantidad y datos completos', 2.5, Math.min(1, n / min) * 2.5, n + ' de ' + min + ' artículos completos (pueden llegar a 5)'],
      ['Actualidad (desde 2020)', 1.5, n ? ok.filter(a => Number(a.anio) >= 2020).length / base * 1.5 : 0, ok.filter(a => Number(a.anio) >= 2020).length + ' artículos desde 2020'],
      ['Fuentes académicas citadas', 1.5, n ? ok.filter(a => Number(a.citas) >= 5 && !/blogspot|wordpress|wikipedia|youtube|tiktok/.test(a.enlace)).length / base * 1.5 : 0, 'Artículos con 5 o más citas y de origen académico'],
      ['Citas APA correctas', 2, n ? sinErr.filter(a => /\(\s*\d{4}[a-z]?\s*\)/.test(a.apa) && a.apa.length > 40).length / base * 2 : 0, 'Autor, (año), título y revista'],
      ['Valoración justificada', 1.5, n ? ok.filter(a => a.por.trim().length >= 40).length / base * 1.5 : 0, 'Matriz completa y una justificación clara'],
      ['Enlaces válidos y sin repetir', 1, n ? Math.max(0, sinErr.length - dup) / base : 0, dup ? dup + ' artículo repetido' : 'Cada enlace lleva a un artículo distinto']];
    R.forEach(r => { r[2] = Math.round(Math.min(r[1], r[2]) * 100) / 100; });
    return { R, nota: Math.round(R.reduce((s, r) => s + r[2], 0) * 100) / 100, n };
  }
  const total = a => a.m.reduce((s, v) => s + (v || 0), 0);
  function make(React, c) {
    const { useState, useEffect, useRef } = React, h = React.createElement, t = c.t, HD = "'Archivo Black',sans-serif", MO = "'IBM Plex Mono',monospace";
    const D = (st, ...ch) => h('div', { style: st }, ...ch), K = (s, col) => D({ fontFamily: MO, fontSize: 13, letterSpacing: '.14em', fontWeight: 700, color: col || t.mute, textTransform: 'uppercase' }, s);
    const T = (s, st) => D(Object.assign({ fontSize: 'clamp(16px,1.4vw,22px)', lineHeight: 1.45 }, st || {}), s), H1 = (s, st) => D(Object.assign({ fontFamily: HD, fontSize: 'clamp(28px,3.2vw,54px)', lineHeight: 1.05 }, st || {}), s);
    const Card = (st, ...ch) => D(Object.assign({ background: t.card, border: '2px solid ' + t.line, borderRadius: 12, padding: 'clamp(14px,1.4vw,22px)', display: 'flex', flexDirection: 'column', gap: 10, minWidth: 0 }, st || {}), ...ch);
    const Btn = (s, on, o) => { o = o || {}; return h('button', { onClick: on, disabled: o.dis, style: { alignSelf: o.self || 'flex-start', background: o.dis ? t.sunk : o.bg || t.acc, color: o.dis ? t.mute : o.c || t.accInk, border: '2px solid ' + (o.bd || (o.dis ? t.line : o.bg || t.acc)), fontFamily: HD, fontSize: o.fs || 17, padding: o.pad || '10px 16px', borderRadius: 8, cursor: o.dis ? 'default' : 'pointer', textAlign: 'left', lineHeight: 1.2 } }, s); };
    const Chip = (s, on, clk, col) => h('button', { onClick: clk, style: { padding: '8px 14px', borderRadius: 999, fontWeight: 700, fontSize: 15, cursor: 'pointer', background: on ? col || t.acc : t.card, color: on ? '#fff' : t.ink, border: '2px solid ' + (on ? col || t.acc : t.line) } }, s);
    const Grid = (min, ...ch) => D({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,' + min + 'px),1fr))', gap: 16, alignItems: 'start' }, ...ch);
    const inp = (v, on, ph, st) => h('input', { value: v, onChange: e => on(e.target.value), placeholder: ph, style: Object.assign({ width: '100%', fontSize: 17, padding: '10px 12px', border: '2px solid ' + t.line, borderRadius: 8, background: t.input, color: t.ink }, st || {}) });
    const area = (v, on, ph) => h('textarea', { value: v, onChange: e => on(e.target.value), placeholder: ph, rows: 3, style: { width: '100%', fontSize: 16, padding: '10px 12px', border: '2px solid ' + t.line, borderRadius: 8, background: t.input, color: t.ink, resize: 'vertical' } });
    const scholar = (q, desde) => 'https://scholar.google.com/scholar?hl=es&q=' + encodeURIComponent(q) + (desde ? '&as_ylo=2020' : '');
    const PASOS = [['tema', '1 · Tema'], ['sim', '2 · Entrenamiento'], ['tabla', '3 · Investigación'], ['pres', '4 · Presentar y entregar']];

    function Rubrica({ ev, min }) {
      return Card({ borderColor: t.acc }, h('div', { style: { display: 'flex', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap', alignItems: 'baseline' } }, K('Rúbrica de la investigación · se calcula mientras trabajan', t.acc), D({ fontFamily: HD, fontSize: 'clamp(26px,2.6vw,40px)', color: ev.nota >= 7 ? t.ok : t.amb }, ev.nota + ' / 10')),
        ...ev.R.map(([n, mx, v, d], i) => D({ key: i, display: 'flex', flexDirection: 'column', gap: 4, borderTop: '2px solid ' + t.line, paddingTop: 8 },
          D({ display: 'flex', justifyContent: 'space-between', gap: 10, fontWeight: 700, fontSize: 16 }, h('span', null, n), h('span', { style: { fontFamily: MO, whiteSpace: 'nowrap' } }, v + ' / ' + mx)),
          D({ height: 8, background: t.sunk, borderRadius: 4 }, D({ height: '100%', width: (v / mx * 100) + '%', background: v >= mx * 0.8 ? t.ok : t.amb, borderRadius: 4, transition: 'width .4s' })), D({ fontSize: 14, color: t.mute }, d))),
        T('Mínimo ' + min + ' artículos. Pueden registrar hasta 5: la nota se calcula con los mejores y suman variedad.', { fontSize: 15, color: t.mute }));
    }
    function Simulador({ onDone, hecho }) {
      const [q, setQ] = useState('redes sociales ansiedad'), [comillas, setCom] = useState(false), [desde, setDesde] = useState(false), [orden, setOrden] = useState('rel'), [cita, setCita] = useState(null), [elig, setElig] = useState(null), [tareas, setTar] = useState({});
      const tk = k => setTar(x => Object.assign({}, x, { [k]: true }));
      let L = SIM.filter(a => norm(q).split(' ').filter(Boolean).every(w => norm(a.k + ' ' + a.t).includes(w)));
      if (comillas) L = L.filter(a => norm(a.t + ' ' + a.k).includes(norm(q)));
      if (desde) L = L.filter(a => a.y >= 2020);
      if (orden === 'cit') L = L.slice().sort((a, b) => b.c - a.c);
      const meta = SIM.filter(a => a.y >= 2020 && a.pdf).sort((a, b) => b.c - a.c)[0];
      const TAR = [['com', 'Usen comillas para buscar la frase exacta'], ['desde', 'Filtren «Desde 2020»'], ['cit', 'Ordenen o comparen por «Citado por»'], ['citar', 'Abran «Citar» y miren la cita APA'], ['elegir', 'Elijan el artículo más citado desde 2020 con PDF']];
      const apa = a => a.a.split(', ').map(n => { const p = n.split(' '); return p.slice(1).join(' ') + ', ' + p[0] + '.'; }).join(', & ') + ' (' + a.y + '). ' + a.t + '. ' + a.r + '.';
      const listo = TAR.every(([k]) => tareas[k]);
      useEffect(() => { if (listo && !hecho) onDone(); }, [listo]);
      return D({ display: 'flex', flexDirection: 'column', gap: 16 },
        K('Entrenamiento · simulador de Google Académico (artículos de práctica, no reales)', t.blue), H1('Aprendan a buscar como en la universidad'),
        Grid(260, ...TAR.map(([k, s], i) => D({ key: k, display: 'flex', gap: 10, alignItems: 'center', padding: '10px 12px', borderRadius: 10, border: '2px solid ' + (tareas[k] ? t.ok : t.line), background: tareas[k] ? t.okBg : t.card } , D({ flex: 'none', width: 28, height: 28, borderRadius: 14, background: tareas[k] ? t.ok : t.sunk, color: '#fff', fontFamily: HD, display: 'flex', alignItems: 'center', justifyContent: 'center' }, tareas[k] ? '✓' : String(i + 1)), T(s, { fontSize: 16 })))),
        h('div', { style: { background: '#ffffff', color: '#202124', border: '2px solid ' + t.line, borderRadius: 12, overflow: 'hidden', fontFamily: 'Arial, sans-serif' } },
          D({ display: 'flex', flexWrap: 'wrap', gap: 12, alignItems: 'center', padding: '14px 18px', borderBottom: '1px solid #dadce0' }, D({ fontSize: 22, fontWeight: 700, color: '#4285f4' }, 'Google ', h('span', { style: { color: '#5f6368', fontWeight: 400 } }, 'Académico')),
            h('div', { style: { flex: '1 1 300px', display: 'flex', alignItems: 'center', border: '1px solid #dadce0', borderRadius: 24, padding: '4px 6px 4px 16px', gap: 6 } }, h('input', { value: comillas ? '"' + q + '"' : q, onChange: e => { const v = e.target.value; const cm = /^".*"$/.test(v.trim()); setCom(cm); if (cm) tk('com'); setQ(v.replace(/"/g, '')); }, style: { flex: 1, minWidth: 0, border: 'none', outline: 'none', fontSize: 17, color: '#202124', background: 'transparent' } }),
              h('button', { onClick: () => { setCom(!comillas); tk('com'); }, style: { border: '1px solid #dadce0', background: comillas ? '#e8f0fe' : '#fff', borderRadius: 16, padding: '4px 10px', cursor: 'pointer', fontSize: 14, color: '#1a73e8' } }, '" " frase exacta'))),
          D({ display: 'grid', gridTemplateColumns: 'minmax(150px,200px) minmax(0,1fr)', gap: 0 },
            D({ padding: '14px 16px', borderRight: '1px solid #dadce0', display: 'flex', flexDirection: 'column', gap: 8, fontSize: 15 }, ...[['Cualquier momento', false], ['Desde 2020', true]].map(([s, v]) => h('button', { key: s, onClick: () => { setDesde(v); if (v) tk('desde'); }, style: { textAlign: 'left', border: 'none', background: 'none', cursor: 'pointer', fontSize: 15, padding: 0, color: desde === v ? '#d93025' : '#1a0dab', fontWeight: desde === v ? 700 : 400 } }, s)),
              D({ height: 1, background: '#dadce0', margin: '6px 0' }), ...[['Ordenar por relevancia', 'rel'], ['Más citados primero', 'cit']].map(([s, v]) => h('button', { key: v, onClick: () => { setOrden(v); if (v === 'cit') tk('cit'); }, style: { textAlign: 'left', border: 'none', background: 'none', cursor: 'pointer', fontSize: 15, padding: 0, color: orden === v ? '#d93025' : '#1a0dab', fontWeight: orden === v ? 700 : 400 } }, s)), D({ fontSize: 12, color: '#5f6368', marginTop: 6 }, '(En el Google Académico real se ordena por relevancia; los más citados se reconocen mirando «Citado por».)')),
            D({ padding: '10px 18px', display: 'flex', flexDirection: 'column', gap: 4, minWidth: 0 }, D({ fontSize: 13, color: '#5f6368' }, 'Aproximadamente ' + L.length + ' resultados'),
              ...(L.length ? L.map((a, i) => D({ key: a.t, display: 'flex', gap: 14, padding: '10px 0', borderBottom: '1px solid #f1f3f4', background: elig === a ? '#fef7e0' : 'transparent' },
                D({ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 3 }, h('button', { onClick: () => { setElig(a); if (a === meta) tk('elegir'); }, style: { textAlign: 'left', border: 'none', background: 'none', padding: 0, cursor: 'pointer', fontSize: 18, color: '#1a0dab' } }, a.t), D({ fontSize: 14, color: '#006621' }, a.a + ' - ' + a.r + ', ' + a.y),
                  D({ display: 'flex', gap: 16, fontSize: 14, color: '#1a0dab', flexWrap: 'wrap' }, h('button', { onClick: () => { setCita(a); tk('citar'); }, style: { border: 'none', background: 'none', padding: 0, cursor: 'pointer', color: '#1a0dab', fontSize: 14 } }, '❝ Citar'), h('span', { onMouseEnter: () => tk('cit'), style: { fontWeight: a.c > 100 ? 700 : 400 } }, 'Citado por ' + a.c), h('span', { style: { color: '#5f6368' } }, 'Artículos relacionados'))),
                a.pdf ? D({ flex: 'none', fontSize: 14, color: '#1a0dab', fontWeight: 700 }, '[PDF] ' + a.r.split(' ')[0].toLowerCase() + '.edu') : null)) : [D({ padding: 20, color: '#5f6368' }, 'Sin resultados. Prueben con menos palabras o quiten las comillas.')])))),
        cita ? Card({ borderColor: t.blue }, K('Cita en formato APA · así la copian del botón «Citar»', t.blue), T(apa(cita), { fontFamily: 'Georgia, serif' }), T('Fíjense: Apellido, inicial. (año). Título. Revista.', { color: t.mute, fontSize: 15 })) : null,
        elig ? T(elig === meta ? '✓ Correcto: es el más citado desde 2020 y tiene PDF disponible.' : elig.y < 2020 ? 'Ese es de ' + elig.y + ': apliquen el filtro «Desde 2020».' : !elig.pdf ? 'No tiene PDF: elijan uno que puedan leer completo.' : elig.c === 0 ? 'Es un blog sin citas: no es académico.' : 'Hay otro desde 2020, con PDF y más citado. Comparen «Citado por».', { fontWeight: 700, color: elig === meta ? t.ok : t.red }) : null,
        listo ? Card({ borderColor: t.ok, background: t.okBg }, H1('¡Entrenamiento completo!', { fontSize: 'clamp(22px,2.2vw,34px)', color: t.ok }), T('Ahora hagan lo mismo en el Google Académico real con su tema.')) : null);
    }
    function Articulo({ a, set, i, ad, quitar }) {
      const w = avisos(a), [g, setG] = useState(0), F = ad ? [CAMPOS[g]] : CAMPOS, up = (k, v) => set(Object.assign({}, a, { [k]: v }));
      const campo = ([k, n, ej]) => D({ key: k, display: 'flex', flexDirection: 'column', gap: 4, gridColumn: k === 'apa' || k === 'titulo' ? '1 / -1' : 'auto' }, K(n, t.ink),
        k === 'acceso' ? D({ display: 'flex', gap: 8, flexWrap: 'wrap' }, Chip('Abierto (PDF gratis)', a.acceso === 'abierto', () => up('acceso', 'abierto'), t.ok), Chip('Restringido', a.acceso === 'restringido', () => up('acceso', 'restringido'), t.amb)) : k === 'apa' ? area(a.apa, v => up('apa', v), 'Ej.: ' + ej) : inp(a[k], v => up(k, v), 'Ej.: ' + ej, k === 'anio' || k === 'citas' ? { fontFamily: MO } : null));
      return Card({ borderColor: completo(a) ? t.ok : t.line, gap: 14 },
        D({ display: 'flex', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap', alignItems: 'center' }, D({ fontFamily: HD, fontSize: 22 }, 'Artículo ' + (i + 1) + (completo(a) ? ' ✓' : '')), quitar ? Btn('Quitar', quitar, { bg: t.card, c: t.red, bd: t.red, fs: 14, pad: '6px 12px' }) : null),
        ad ? D({ display: 'flex', gap: 6, flexWrap: 'wrap' }, ...CAMPOS.map(([k, n], j) => Chip((String(a[k] || '').trim() ? '✓ ' : '') + n.split(' (')[0], g === j, () => setG(j), t.blue))) : null,
        D({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,240px),1fr))', gap: 12 }, ...F.map(campo)),
        ad ? D({ display: 'flex', gap: 8 }, Btn('◀ Anterior', () => setG(Math.max(0, g - 1)), { bg: t.card, c: t.ink, bd: t.line, fs: 15, dis: g === 0 }), Btn('Siguiente ▶', () => setG(Math.min(CAMPOS.length - 1, g + 1)), { bg: t.blue, c: '#fff', fs: 15, dis: g === CAMPOS.length - 1 })) : null,
        D({ display: 'flex', flexDirection: 'column', gap: 8, borderTop: '2px solid ' + t.line, paddingTop: 12 }, K('Matriz de valoración · 0 no cumple · 1 parcial · 2 cumple', t.acc),
          D({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,190px),1fr))', gap: 8 }, ...CRIT.map((cr, j) => D({ key: cr, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 6, padding: '6px 10px', border: '1px solid ' + t.line, borderRadius: 8 }, h('span', { style: { fontWeight: 600, fontSize: 15 } }, cr), D({ display: 'flex', gap: 4 }, ...[0, 1, 2].map(v => h('button', { key: v, onClick: () => { const m = a.m.slice(); m[j] = v; up('m', m); }, style: { width: 32, height: 32, borderRadius: 6, fontFamily: HD, cursor: 'pointer', border: '2px solid ' + (a.m[j] === v ? [t.red, t.amb, t.ok][v] : t.line), background: a.m[j] === v ? [t.red, t.amb, t.ok][v] : t.card, color: a.m[j] === v ? '#fff' : t.ink } }, String(v))))))),
          D({ fontFamily: MO, fontWeight: 700 }, 'Total: ' + total(a) + ' / 12' + (a.m.every(v => v != null) ? total(a) >= 9 ? ' · fuente sólida' : total(a) >= 6 ? ' · usar con precaución' : ' · mejor descartarla' : '')),
          K('¿Por qué lo eligen? (una o dos oraciones)', t.ink), area(a.por, v => up('por', v), 'Ej.: Es reciente (2023), lo publica una revista universitaria, tiene 45 citas y responde directamente a nuestra pregunta.')),
        w.length ? D({ display: 'flex', flexDirection: 'column', gap: 6 }, ...w.map(([k, s], j) => D({ key: j, padding: '8px 12px', borderRadius: 8, fontSize: 15, fontWeight: 600, background: k === 'err' ? t.errBg : t.sunk, color: k === 'err' ? t.red : t.amb, border: '1px solid ' + (k === 'err' ? t.red : t.amb) }, (k === 'err' ? '✗ ' : '⚠ ') + s))) : null);
    }
    function imprimir(inv, nombres, ev, tema) {
      const w = window.open('', '_blank'); if (!w) { alert('Permitan las ventanas emergentes para imprimir.'); return; }
      const esc = s => String(s || '').replace(/[&<>]/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[x]));
      w.document.write('<html><head><title>Investigación · ' + esc(nombres) + '</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}table{border-collapse:collapse;width:100%;font-size:11px}td,th{border:1px solid #444;padding:5px;vertical-align:top;text-align:left}th{background:#eee}h1{font-size:20px;margin:0 0 4px}p{margin:4px 0}</style></head><body><h1>Tabla de investigación · ' + esc(tema[1]) + '</h1><p><b>Pregunta:</b> ' + esc(tema[2]) + '</p><p><b>Integrantes:</b> ' + esc(nombres) + ' · <b>Nota de la tabla:</b> ' + ev.nota + ' / 10</p><table><tr><th>#</th><th>Título</th><th>Autores</th><th>Año</th><th>Revista</th><th>Citado por</th><th>Acceso</th><th>Cita APA</th><th>Enlace</th><th>Matriz</th><th>Justificación</th></tr>' + inv.arts.filter(completo).map((a, i) => '<tr><td>' + (i + 1) + '</td><td>' + esc(a.titulo) + '</td><td>' + esc(a.autores) + '</td><td>' + esc(a.anio) + '</td><td>' + esc(a.revista) + '</td><td>' + esc(a.citas) + '</td><td>' + esc(a.acceso) + '</td><td>' + esc(a.apa) + '</td><td>' + esc(a.enlace) + '</td><td>' + total(a) + '/12</td><td>' + esc(a.por) + '</td></tr>').join('') + '</table>' + (inv.mejor != null ? '<p style="margin-top:12px"><b>Artículo destacado:</b> ' + esc((inv.arts[inv.mejor] || {}).titulo) + '. ' + esc(inv.expo) + '</p>' : '') + '<script>setTimeout(function(){print()},300)<\/script></body></html>'); w.document.close();
    }
    function Estudiante(p) {
      const inv = p.inv || { paso: 'tema', tema: null, arts: [vacio(), vacio(), vacio()], sim: false, mejor: null, expo: '', entregado: false }, set = x => p.setInv(Object.assign({}, inv, x)), min = p.adaptado ? 2 : 3, ev = evaluar(inv.arts, min), tema = TEMAS.find(x => x[0] === inv.tema);
      const guardar = () => p.send(inv, ev); const tm = useRef(null);
      useEffect(() => { clearTimeout(tm.current); tm.current = setTimeout(guardar, 2500); return () => clearTimeout(tm.current); }, [JSON.stringify(inv.arts), inv.tema, inv.mejor, inv.expo]);
      const nav = D({ display: 'flex', gap: 8, flexWrap: 'wrap' }, ...PASOS.map(([k, n]) => Chip(n, inv.paso === k, () => set({ paso: k }), t.blue)));
      const cab = D({ display: 'flex', flexDirection: 'column', gap: 10 }, K('Misión investigador universitario · el docente abrió la investigación', t.acc), nav);
      if (inv.paso === 'tema') return D({ display: 'flex', flexDirection: 'column', gap: 18 }, cab, H1('Elijan el tema que más les interese'), T('Cada tema trae una pregunta de investigación y palabras clave en español e inglés. Buscar en inglés da muchos más artículos.'),
        Grid(270, ...TEMAS.map(x => h('button', { key: x[0], onClick: () => set({ tema: x[0] }), style: { textAlign: 'left', background: inv.tema === x[0] ? t.okBg : t.card, color: t.ink, border: '3px solid ' + (inv.tema === x[0] ? t.ok : t.line), borderRadius: 12, padding: 16, cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: 8 } }, D({ fontFamily: HD, fontSize: 21, lineHeight: 1.1 }, x[1]), D({ fontSize: 16, lineHeight: 1.4 }, x[2]), inv.tema === x[0] ? D({ fontFamily: MO, fontWeight: 700, color: t.ok, fontSize: 13 }, '✓ ELEGIDO') : null))),
        tema ? Btn('Siguiente: entrenamiento de búsqueda ▶', () => set({ paso: 'sim' }), { fs: 19, pad: '14px 22px' }) : null);
      if (inv.paso === 'sim') return D({ display: 'flex', flexDirection: 'column', gap: 18 }, cab, h(Simulador, { hecho: inv.sim, onDone: () => set({ sim: true }) }), Btn(inv.sim ? 'Ir a la investigación real ▶' : 'Saltar el entrenamiento ▶', () => set({ paso: 'tabla' }), { fs: 19, pad: '14px 22px', bg: inv.sim ? t.acc : t.card, c: inv.sim ? t.accInk : t.ink, bd: t.line }));
      if (inv.paso === 'tabla') return D({ display: 'flex', flexDirection: 'column', gap: 18 }, cab,
        !tema ? Card({ borderColor: t.red }, T('Primero elijan un tema.', { color: t.red, fontWeight: 700 }), Btn('Elegir tema', () => set({ paso: 'tema' }))) : null,
        tema ? Grid(380, Card({ borderColor: t.blue }, K('Su tema', t.blue), D({ fontFamily: HD, fontSize: 24 }, tema[1]), T(tema[2]), K('Busquen en Google Académico'), ...tema[3].map((q, j) => D({ key: j, display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }, D({ fontFamily: MO, fontSize: 15, background: t.sunk, padding: '6px 10px', borderRadius: 6, overflowWrap: 'anywhere' }, q), h('a', { href: scholar(q, true), target: '_blank', rel: 'noopener', style: { background: t.blue, color: '#fff', padding: '8px 14px', borderRadius: 8, fontWeight: 700, fontSize: 15, textDecoration: 'none' } }, 'Abrir búsqueda (desde 2020) ↗'))),
          T('Consejos: revisen «Citado por», prefieran los que tienen [PDF], abran el artículo antes de registrarlo y copien la cita del botón «Citar» → APA.', { fontSize: 15, color: t.mute })), h(Rubrica, { ev, min })) : null,
        ...inv.arts.map((a, i) => h(Articulo, { key: i, a, i, ad: p.adaptado, set: na => { const L = inv.arts.slice(); L[i] = na; set({ arts: L }); }, quitar: inv.arts.length > min ? () => set({ arts: inv.arts.filter((_, j) => j !== i), mejor: null }) : null })),
        D({ display: 'flex', gap: 10, flexWrap: 'wrap' }, inv.arts.length < 5 ? Btn('+ Agregar otro artículo (' + inv.arts.length + ' / 5)', () => set({ arts: inv.arts.concat([vacio()]) }), { bg: t.card, c: t.acc, bd: t.acc }) : null, Btn('Siguiente: presentar ▶', () => set({ paso: 'pres' }), { dis: ev.n < min })),
        ev.n < min ? T('Completen al menos ' + min + ' artículos (todos los campos, la matriz y la justificación) para continuar.', { color: t.amb, fontWeight: 600 }) : null);
      const ok = inv.arts.map((a, i) => [a, i]).filter(([a]) => completo(a));
      return D({ display: 'flex', flexDirection: 'column', gap: 18 }, cab, H1('Presenten su mejor hallazgo'), T('Elijan el artículo más valioso y preparen una justificación de 1 minuto para el curso.'),
        Grid(280, ...ok.map(([a, i]) => h('button', { key: i, onClick: () => set({ mejor: i }), style: { textAlign: 'left', background: inv.mejor === i ? t.okBg : t.card, color: t.ink, border: '3px solid ' + (inv.mejor === i ? t.ok : t.line), borderRadius: 12, padding: 14, cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: 6 } }, D({ fontWeight: 700, fontSize: 17 }, a.titulo), D({ fontFamily: MO, fontSize: 14, color: t.mute }, a.anio + ' · citado por ' + a.citas + ' · matriz ' + total(a) + '/12')))),
        Card({}, K('Su justificación (lo que dirán en 1 minuto)'), area(inv.expo, v => set({ expo: v }), 'Elegimos este artículo porque… (criterios: autor, fecha, revista, citas, evidencia)')),
        h(Rubrica, { ev, min }),
        D({ display: 'flex', gap: 10, flexWrap: 'wrap' }, Btn(inv.entregado ? '✓ Investigación entregada · reenviar' : 'Entregar la investigación (' + ev.nota + ' / 10)', () => { if (inv.mejor == null || inv.expo.trim().length < 20) { alert('Elijan su mejor artículo y escriban la justificación.'); return; } set({ entregado: true }); p.entregar(inv, ev); }, { fs: 19, pad: '14px 22px', dis: ev.n < min }), Btn('Imprimir / guardar en PDF', () => imprimir(inv, p.nombres, ev, tema || TEMAS[0]), { bg: t.card, c: t.ink, bd: t.line, dis: !ev.n })));
    }
    function Docente(p) {
      const res = (p.res && p.res.inv) || {}, [vista, setV] = useState('parejas'), [rul, setRul] = useState(null);
      const L = Object.keys(res).map(k => { let d = null; try { d = JSON.parse(res[k].r); } catch (e) {} return d ? Object.assign({ pareja: k }, d) : null; }).filter(Boolean);
      const arts = []; L.forEach(x => (x.arts || []).filter(completo).forEach(a => arts.push(Object.assign({ pareja: x.nombres || x.pareja, tema: x.tema }, a))));
      const top = (f, lab) => { const a = arts.slice().sort((x, y) => f(y) - f(x))[0]; return Card({ borderColor: t.acc }, K(lab, t.acc), a ? D({ fontFamily: HD, fontSize: 20, lineHeight: 1.15 }, a.titulo) : T('—'), a ? T(a.pareja + ' · ' + a.anio + ' · citado por ' + a.citas + ' · matriz ' + total(a) + '/12', { fontSize: 15, color: t.mute }) : null); };
      const grupos = {}; arts.forEach(a => { const k = norm(a.titulo); (grupos[k] = grupos[k] || []).push(a); }); const rep = Object.values(grupos).filter(g => new Set(g.map(x => x.pareja)).size > 1);
      const csv = () => { const q = s => '"' + String(s == null ? '' : s).replace(/"/g, '""') + '"'; const rows = [['Pareja', 'Tema', 'Nota tabla', 'Título', 'Autores', 'Año', 'Revista', 'Citado por', 'Acceso', 'Cita APA', 'Enlace', ...CRIT, 'Total matriz', 'Justificación', 'Destacado', 'Exposición']];
        L.forEach(x => (x.arts || []).filter(completo).forEach((a, i) => rows.push([x.nombres || x.pareja, (TEMAS.find(z => z[0] === x.tema) || [])[1], x.nota, a.titulo, a.autores, a.anio, a.revista, a.citas, a.acceso, a.apa, a.enlace, ...a.m, total(a), a.por, x.mejor === i ? 'sí' : '', x.mejor === i ? x.expo : ''])));
        const b = new Blob(['\ufeff' + rows.map(r => r.map(q).join(';')).join('\r\n')], { type: 'text/csv;charset=utf-8' }), u = URL.createObjectURL(b), e = document.createElement('a'); e.href = u; e.download = 'investigacion_3BGU_' + new Date().toISOString().slice(0, 10) + '.csv'; e.click(); setTimeout(() => URL.revokeObjectURL(u), 1000); };
      const conMejor = L.filter(x => x.mejor != null && x.arts && x.arts[x.mejor]);
      return D({ display: 'flex', flexDirection: 'column', gap: 18 },
        D({ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap', alignItems: 'center' }, H1('Investigación en curso · ' + L.length + ' parejas'), D({ display: 'flex', gap: 8, flexWrap: 'wrap' }, Chip('Parejas', vista === 'parejas', () => setV('parejas')), Chip('Comparación del curso', vista === 'comp', () => setV('comp')), Chip('Presentaciones', vista === 'pres', () => setV('pres')), Btn('Descargar Excel (CSV)', csv, { fs: 15, pad: '8px 14px', dis: !arts.length }))),
        T('Durante esta fase los estudiantes pueden abrir Google Académico. Las tablas se guardan solas cada pocos segundos.', { color: t.mute, fontSize: 16 }),
        vista === 'parejas' ? Card({}, ...(L.length ? L.map((x, i) => D({ key: i, display: 'grid', gridTemplateColumns: 'minmax(0,2fr) minmax(0,2fr) auto auto', gap: 10, alignItems: 'center', borderTop: i ? '1px solid ' + t.line : 'none', paddingTop: i ? 8 : 0, fontSize: 16 }, D({ fontWeight: 700 }, x.nombres || x.pareja), D({}, (TEMAS.find(z => z[0] === x.tema) || ['', 'sin tema'])[1]), D({ fontFamily: MO, whiteSpace: 'nowrap' }, (x.arts || []).filter(completo).length + ' art.'), D({ fontFamily: HD, color: x.entregado ? t.ok : t.amb, whiteSpace: 'nowrap' }, (x.entregado ? '✓ ' : '') + x.nota + '/10'))) : [T('Todavía no hay tablas guardadas.')])) : null,
        vista === 'comp' ? D({ display: 'flex', flexDirection: 'column', gap: 16 }, Grid(300, top(a => Number(a.citas) || 0, 'El más citado'), top(a => Number(a.anio) || 0, 'El más reciente'), top(a => total(a) * 1000 + (Number(a.citas) || 0), 'El mejor valorado')),
          Card({ borderColor: t.amb }, K('Mismo artículo, distintas parejas · ¿lo valoraron igual?', t.amb), ...(rep.length ? rep.map((g, i) => D({ key: i, display: 'flex', flexDirection: 'column', gap: 4, borderTop: '1px solid ' + t.line, paddingTop: 8 }, D({ fontWeight: 700 }, g[0].titulo), ...g.map((a, j) => D({ key: j, fontSize: 15, fontFamily: MO }, a.pareja + ' → ' + total(a) + '/12')))) : [T('Ninguna pareja repitió artículo.', { color: t.mute })])),
          Card({}, K('Artículos por año'), D({ display: 'flex', gap: 6, alignItems: 'flex-end', height: 140 }, ...(() => { const c = {}; arts.forEach(a => { c[a.anio] = (c[a.anio] || 0) + 1; }); const ks = Object.keys(c).sort(), mx = Math.max(1, ...Object.values(c)); return ks.map(k => D({ key: k, flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }, D({ fontFamily: MO, fontSize: 13 }, String(c[k])), D({ width: '100%', height: c[k] / mx * 100, background: Number(k) >= 2020 ? t.acc : t.amb, borderRadius: 4 }), D({ fontFamily: MO, fontSize: 12 }, k))); })()))) : null,
        vista === 'pres' ? D({ display: 'flex', flexDirection: 'column', gap: 16 }, Btn('🎲 Ruleta: ¿quién presenta?', () => { if (!conMejor.length) return; let n = 0; const go = () => { setRul(Math.floor(Math.random() * conMejor.length)); if (++n < 14) setTimeout(go, 60 + n * 18); }; go(); }, { fs: 20, pad: '14px 22px', dis: !conMejor.length }),
          rul != null && conMejor[rul] ? Card({ borderColor: t.acc, gap: 12 }, K('Presenta', t.acc), D({ fontFamily: HD, fontSize: 'clamp(26px,3vw,48px)' }, conMejor[rul].nombres || conMejor[rul].pareja), D({ fontSize: 'clamp(19px,1.8vw,28px)', fontWeight: 700 }, conMejor[rul].arts[conMejor[rul].mejor].titulo), T(conMejor[rul].arts[conMejor[rul].mejor].revista + ' · ' + conMejor[rul].arts[conMejor[rul].mejor].anio + ' · citado por ' + conMejor[rul].arts[conMejor[rul].mejor].citas, { color: t.mute }), T('«' + conMejor[rul].expo + '»', { fontStyle: 'italic' }), T('Pregunta al curso: ¿qué criterio de la matriz los convence más? ¿Hay alguno débil?', { color: t.blue, fontWeight: 600 })) : null,
          Grid(320, ...conMejor.map((x, i) => Card({ key: i }, D({ fontWeight: 700 }, x.nombres || x.pareja), T(x.arts[x.mejor].titulo, { fontSize: 16 }))))) : null);
    }
    return { Estudiante, Docente, TEMAS, evaluar };
  }
  window.CLASE3_INV = { make, TEMAS, evaluar, completo };
})();
